<template>
 <f7-page class="cy-mobile-surface cy-asset-tools" @page:afterin="load">
  <f7-navbar :title="editing?'定期存款':title" :back-link="editing?undefined:'资产'"><f7-nav-left v-if="editing"><f7-link icon-f7="xmark" :disabled="busy" @click="editing=null"/></f7-nav-left><f7-nav-right><f7-link v-if="tool==='deposits'&&!editing" icon-f7="plus" aria-label="添加定存" @click="newDeposit"/><f7-link v-if="editing" icon-f7="checkmark" aria-label="保存定存" :disabled="busy" @click="saveDeposit"/></f7-nav-right></f7-navbar>
  <main class="cy-page-body">
   <p v-if="error" class="cy-message" role="alert">{{error}} <button @click="load">重试</button></p>
   <p v-if="loading" class="cy-empty" role="status">正在加载…</p>
   <template v-else>
    <template v-if="tool==='search'"><label class="tool-search"><f7-icon f7="search"/><input v-model="search" aria-label="搜索账户名称" placeholder="搜索账户名称" autofocus/><button v-if="search" @click="search=''">清除</button></label><p v-if="!searched.length" class="cy-empty">没有找到匹配账户</p><section class="cy-panel tool-account-list"><f7-link v-for="a in searched" :key="a.key" :href="a.href"><span>{{a.name}}<small v-if="a.hidden">已隐藏</small></span><strong>{{money(a.balance)}}<small>{{a.currency}}</small></strong></f7-link></section></template>
    <template v-else-if="tool==='books'"><section class="cy-panel"><label class="field">生效账本<select v-model="selectedBook" aria-label="选择生效账本"><option v-for="b in books.allBooks" :key="b.id" :value="b.id">{{b.name}}</option></select></label><p class="hint">勾选的账户可在这个账本记账时选择。账户余额仍在全部账本间共用，已有流水保留。</p><label v-for="a in items" :key="a.key" class="choice"><input type="checkbox" :checked="available(a.key)" @change="setBook(a.key,($event.target as HTMLInputElement).checked)"/><span>{{a.name}}</span><small>{{a.portfolio?'投资':'资金'}}</small></label><button class="primary" :disabled="busy" @click="savePreferences">{{busy?'正在保存…':'保存生效账本'}}</button></section></template>
    <template v-else-if="tool==='hidden'"><section class="cy-panel"><p class="hint">隐藏只控制列表展示，仍计入资产汇总。需要排除金额时，请在账户或持仓编辑中关闭“计入总资产”。</p><label v-for="a in items" :key="a.key" class="choice"><span>{{a.name}}</span><small>{{money(a.balance)}} {{a.currency}}</small><input type="checkbox" :checked="!draft.rules[a.key]?.hidden" :aria-label="`显示${a.name}`" @change="rule(a.key).hidden=!($event.target as HTMLInputElement).checked"/></label><p v-if="!items.length" class="cy-empty">还没有账户</p><button class="primary" :disabled="busy" @click="savePreferences">{{busy?'正在保存…':'保存显示设置'}}</button></section></template>
    <template v-else-if="tool==='reminders'"><section class="cy-panel"><label class="choice"><span>还款提醒</span><input v-model="draft.reminders.enabled" type="checkbox" aria-label="开启还款提醒" @change="requestPermission"/></label><div v-if="draft.reminders.enabled"><p class="hint" role="status">{{permissionText}}</p><button v-if="permission==='denied'" class="secondary" @click="requestPermission">允许系统通知</button><label class="choice"><span>信用卡还款</span><input v-model="draft.reminders.credit" type="checkbox"/></label><label class="choice"><span>借入与贷款还款</span><input v-model="draft.reminders.debt" type="checkbox"/></label><label class="choice"><span>定期存款到期</span><input v-model="draft.reminders.deposit" type="checkbox"/></label><label class="field">提前提醒<select v-model.number="draft.reminders.advanceDays" aria-label="提前提醒天数"><option v-for="n in 31" :key="n" :value="n-1">{{n===1?'当天':`提前${n-1}天`}}</option></select></label><label class="field">提醒时间<input v-model="reminderTime" type="time" aria-label="提醒时间"/></label><p class="hint">按会计时区 {{scope.timeZone}} 提醒。系统省电限制可能延迟通知。</p></div><button class="primary" :disabled="busy" @click="savePreferences">保存提醒设置</button><button v-if="draft.reminders.enabled&&permission==='granted'" class="secondary" @click="testNotification">发送测试通知</button></section><section class="cy-panel"><div class="cy-section-head"><h2>待还款事项</h2><f7-link href="/calendar/due">管理到期事项 ›</f7-link></div><p v-if="!repayments.length" class="cy-empty">暂无还款日期，添加到期事项后会自动安排通知。</p><div v-for="d in repayments" :key="d.id" class="data-row"><span>{{d.accountName}}<small>{{d.date}}<span v-if="d.id.startsWith('annual:')"> · 年费</span></small></span><strong>{{money(d.amount)}} {{d.currency}}</strong></div></section></template>
    <template v-else-if="tool==='deposits'">
     <form v-if="editing" class="deposit-edit" @submit.prevent="saveDeposit">
      <section class="cy-panel deposit-fields">
       <label v-if="!accountId">账户<select v-model="editing.accountId" aria-label="定存账户"><option v-for="a in depositAccounts" :key="a.id" :value="a.id">{{a.name}}</option></select></label>
       <label>存入金额<input v-model="editing.principal" inputmode="decimal" placeholder="输入存入金额" maxlength="16" aria-label="定存本金" required/></label>
       <label>年利率<input v-model="editing.annualRate" inputmode="decimal" placeholder="输入年利率" maxlength="10" aria-label="定存年利率" required/><span>%</span></label>
       <label>存期<input v-model.number="editing.term" type="number" min="1" max="36500" placeholder="输入存期" aria-label="定存期限"/><select class="deposit-unit" v-model="editing.unit" aria-label="定存期限单位"><option value="year">年</option><option value="month">月</option><option value="day">天</option></select></label>
       <label>备注<input v-model="editing.note" placeholder="输入备注" maxlength="200" aria-label="定存备注"/></label>
      </section>
      <section class="cy-panel deposit-fields"><label>存入日期<input v-model="editing.startDate" type="date" aria-label="定存开始日期"/></label><div>预计收益<strong>{{money(projectedInterest)}} {{depositCurrency}}</strong></div></section>
      <p class="hint">提示：<br/>定存不会改变当前账户金额，到期后自动生成一笔收益账单。定存本金应包含在账户余额中。</p>
     </form>
     <template v-else>
      <section class="cy-panel deposit-overview"><div><span>定期存款</span><strong>{{money(depositTotal('principal'))}}</strong></div><div><span>预计收益</span><strong>{{money(depositTotal('expectedInterest'))}}</strong></div><div><span>累积收益</span><strong>{{money(depositTotal('receivedInterest'))}}</strong></div><small>{{accountId?accountStore.allAccountsMap[accountId]?.currency:'人民币账户合计；外币按原币列示'}}</small></section>
      <div class="deposit-filters"><select v-model="depositFilter" aria-label="筛选定存"><option value="all">全部定存</option><option value="pending">未到期定存</option><option value="matured">已到期定存</option><option value="closed">已归档 / 终止</option></select><select v-model="depositSort" aria-label="定存排序"><option value="maturityDate">按到期时间</option><option value="startDate">按存款时间</option><option value="principal">按本金</option><option value="annualRate">按利率</option><option value="expectedInterest">按收益</option></select></div>
      <p v-if="!shownDeposits.length" class="cy-empty">当前账户没有任何记录</p>
      <section v-for="d in shownDeposits" :key="d.id" class="cy-panel deposit-record"><div class="cy-section-head"><h2>{{d.note||accountStore.allAccountsMap[d.accountId]?.name||'定期存款'}}</h2><span>{{d.closed?'已归档':d.settled?'收益已入账':d.maturityDate<=today?'已到期':'未到期'}}</span></div><div class="data-row"><span>本金</span><strong>{{money(d.principal)}} {{d.currency}}</strong></div><div class="data-row"><span>年利率 / 存期</span><strong>{{d.annualRate}}% / {{d.term}}{{({day:'天',month:'月',year:'年'})[d.unit]}}</strong></div><div class="data-row"><span>预计收益</span><strong>{{money(d.expectedInterest)}}</strong></div><p class="hint">{{d.startDate}} 至 {{d.maturityDate}}</p><div class="form-actions"><button v-if="!d.settled&&!d.closed" class="secondary" @click="editing={...d}">编辑</button><f7-link v-if="d.transactionId" :href="`/transaction/detail?id=${d.transactionId}`">收益流水</f7-link><button v-if="!d.closed" class="secondary" :disabled="busy" @click="closeDeposit(d)">{{d.settled?'归档':'提前终止'}}</button></div></section>
     </template>
    </template>
    <template v-else-if="tool==='distribution'"><section class="cy-panel"><h2>资产分布</h2><div class="flow-head"><span>负债</span><strong>净资产 {{money(totals.net)}}</strong><span>资产</span></div><svg v-if="distribution.length||liabilities.length" class="asset-flow" viewBox="0 0 340 280" role="img" aria-label="负债与资产分类分布"><path v-for="(a,i) in liabilities" :key="a.key" :d="`M75,${40+i*32} C115,${40+i*32} 115,140 150,140`" stroke="var(--cy-expense)" :stroke-width="flowWidth(a.value)" fill="none" opacity=".45"/><path v-for="(g,i) in distribution" :key="g.name" :d="`M190,140 C225,140 225,${40+i*46} 265,${40+i*46}`" stroke="var(--cy-accent)" :stroke-width="flowWidth(g.value)" fill="none" opacity=".45"/><rect x="151" y="85" width="38" height="110" rx="8" fill="var(--cy-accent)"/><text x="170" y="143" text-anchor="middle" fill="white">资产</text><g v-for="(a,i) in liabilities" :key="a.key"><text x="73" :y="34+i*32" text-anchor="end">{{a.name}}</text></g><g v-for="(g,i) in distribution" :key="g.name"><text x="268" :y="34+i*46">{{g.name}}</text><text x="268" :y="50+i*46">{{money(g.value)}}</text></g></svg><p v-else class="cy-empty">暂无资产与负债</p><p v-if="totals.missing" class="hint">{{totals.missing}} 项缺少估值，未以零计入图表。</p></section><section v-for="g in distribution" :key="g.name" class="cy-panel"><h2>{{g.name}} · {{money(g.value)}}</h2><f7-link v-for="a in g.items" :key="a.key" class="data-row" :href="a.href"><span>{{a.name}}</span><strong>{{money(a.value)}}</strong></f7-link></section></template>
    <template v-else-if="tool==='more'"><section class="cy-panel more-data"><h2>资产数据</h2><div class="data-row"><span>本月总还款</span><strong>{{money(monthRepayment(false))}}</strong></div><div class="data-row"><span>本月剩余待还</span><strong class="cy-expense">{{money(monthRepayment(true))}}</strong></div><div class="data-row"><span>可使用资金</span><strong class="cy-income">{{money(availableCash)}}</strong></div><p class="hint">本月还款包含信用卡待还账单、借款还款日期和手动到期事项；可使用资金为可支配账户正余额，扣除其中尚未到期的定存本金。外币缺少汇率时保持未知。</p><f7-link href="/calendar/due">管理还款日期与金额 ›</f7-link></section></template>
   </template>
  </main>
 </f7-page>
</template>
<script setup lang="ts">
import {assetMoney as ledgerMoney} from '@/lib/asset-visibility.ts';
import {computed,ref} from 'vue';
import {f7} from 'framework7-vue';
import type {Router} from 'framework7/types';
import {assetTools,assetItems,assetTotals,decimalSum,mergeCreditDue,mergeDebtDue,notificationStatus,updateNativeReminders,type FixedDeposit,type AssetPreferences} from '@/lib/asset-tools.ts';
import {useAssetToolsStore} from '@/stores/assetTools.ts';
import {useAccountsStore} from '@/stores/account.ts';
import {useBooksStore} from '@/stores/books.ts';
import {useLedgerScopeStore} from '@/stores/ledgerScope.ts';
import {useTransactionCategoriesStore} from '@/stores/transactionCategory.ts';
import {useTransactionsStore} from '@/stores/transaction.ts';
import {debtAccounts} from '@/lib/debt-accounts.ts';
import {creditAccounts} from '@/lib/credit-accounts.ts';
import {calendarEvents,type CalendarEvent} from '@/lib/calendar-events.ts';
import {investments,investmentError} from '@/lib/investments.ts';
import {LedgerDecimal,keepUpToDate} from '@/lib/mobile-ledger.ts';
import type {WealthSummary,InvestmentAccount} from '@/models/investment.ts';

import moment from 'moment-timezone';
const props=defineProps<{f7route:Router.Route}>();
const accountId=computed(()=>props.f7route.query['accountId']||'');
const tool=computed(()=>props.f7route.query['tool']||'search');
const title=computed(()=>({search:'搜索账户',reminders:'还款提醒',books:'生效账本',deposits:'定存记录',hidden:'资产隐藏',distribution:'资产分布',more:'更多数据'}[tool.value]||'资产'));
const accountStore=useAccountsStore(),books=useBooksStore(),scope=useLedgerScopeStore(),preferences=useAssetToolsStore(),categories=useTransactionCategoriesStore();
const loading=ref(true),busy=ref(false),error=ref(''),search=ref(''),selectedBook=ref(''),permission=ref(notificationStatus()),draft=ref<AssetPreferences>(JSON.parse(JSON.stringify(preferences.preferences)));
const summary=ref<WealthSummary>(),portfolios=ref<InvestmentAccount[]>([]),deposits=ref<FixedDeposit[]>([]),pending=ref<CalendarEvent[]>([]),monthDue=ref<CalendarEvent[]>([]),editing=ref<FixedDeposit|null>(null);
const today=computed(()=>moment().tz(scope.timeZone).format('YYYY-MM-DD')),month=computed(()=>today.value.slice(0,7));
const items=computed(()=>assetItems(summary.value,portfolios.value,accountStore.allAccountsMap,preferences.preferences));
const searched=computed(()=>items.value.filter(a=>a.name.toLocaleLowerCase().includes(search.value.trim().toLocaleLowerCase())));
const totals=computed(()=>assetTotals(items.value));
const repayments=computed(()=>pending.value.filter(d=>d.kind==='repayment'));
const permissionText=computed(()=>permission.value==='granted'?'系统通知已允许，保存后安排提醒。':permission.value==='browser'?'电脑预览仅显示到期事项；系统通知需要 Android 应用。':'系统通知尚未允许，请允许通知后接收提醒。');
const reminderTime=computed({get:()=>`${String(Math.floor(draft.value.reminders.minuteOfDay/60)).padStart(2,'0')}:${String(draft.value.reminders.minuteOfDay%60).padStart(2,'0')}`,set:(v:string)=>{const[h=0,m=0]=v.split(':').map(Number);if(Number.isInteger(h)&&Number.isInteger(m))draft.value.reminders.minuteOfDay=h*60+m;}});
function rule(key:string){return draft.value.rules[key] ||= {hidden:false,disabledBooks:[]};}
function available(key:string){return !rule(key).disabledBooks.includes(selectedBook.value);}
function setBook(key:string,checked:boolean){const r=rule(key);r.disabledBooks=checked?r.disabledBooks.filter(id=>id!==selectedBook.value):[...new Set([...r.disabledBooks,selectedBook.value])];}
function requestPermission(){if(draft.value.reminders.enabled&&notificationStatus()==='denied')window.CYLedgerReminders?.requestPermission();setTimeout(()=>permission.value=notificationStatus(),1000);}
function testNotification(){window.CYLedgerReminders?.test();f7.toast.create({text:'测试通知已安排，可以返回桌面验证',closeTimeout:2500}).open();}
function money(value:string|null|undefined){return ledgerMoney(value,false);}
async function load(){loading.value=true;error.value='';try{await Promise.all([books.loadBooks(),accountStore.loadAllAccounts({force:true}).catch(keepUpToDate),categories.loadAllCategories({force:false}).catch(keepUpToDate),preferences.load(true)]);const[w,p,d,all,due,credit,debts]=await Promise.all([investments.summary(),investments.accounts(),assetTools.deposits(),assetTools.pending(),calendarEvents.list(month.value),creditAccounts.reports(scope.timeZone),debtAccounts.reports()]);summary.value=w;portfolios.value=p;deposits.value=d;pending.value=mergeDebtDue(mergeCreditDue(all,credit),debts,accountStore.allAccountsMap);monthDue.value=mergeDebtDue(mergeCreditDue(due,credit),debts,accountStore.allAccountsMap).filter(d=>d.date.startsWith(month.value));draft.value=JSON.parse(JSON.stringify(preferences.preferences));selectedBook.value ||= books.defaultBookId;permission.value=notificationStatus();}catch(e){error.value=investmentError(e);}finally{loading.value=false;}}
async function savePreferences(){busy.value=true;error.value='';try{await preferences.save(draft.value);await updateNativeReminders(preferences.preferences,accountStore.allAccountsMap,scope.timeZone);draft.value=JSON.parse(JSON.stringify(preferences.preferences));permission.value=notificationStatus();f7.toast.create({text:'设置已保存',closeTimeout:2000}).open();}catch(e){error.value=investmentError(e);}finally{busy.value=false;}}
const depositAccounts=computed(()=>accountStore.allPlainAccounts.filter(a=>!a.isLiability&&a.type===1&&a.assetProfile.kind!=='reimbursement'));

const depositCurrency=computed(()=>accountStore.allAccountsMap[editing.value?.accountId||'']?.currency||'CNY');
function newDeposit(){editing.value={id:'',accountId:accountId.value||depositAccounts.value[0]?.id||'',bookId:books.defaultBookId,categoryId:'',currency:'CNY',principal:'',annualRate:'',term:1,unit:'year',startDate:today.value,maturityDate:'',expectedInterest:'',timeZone:scope.timeZone,note:'',settled:false,transactionId:'',closed:false};}
const projectedInterest=computed(()=>{const d=editing.value;if(!d||!/^\d+(\.\d{1,6})?$/.test(d.principal)||!/^\d+(\.\d{1,6})?$/.test(d.annualRate)||!Number.isInteger(d.term)||d.term<=0)return null;return new LedgerDecimal(d.principal).mul(d.annualRate).div(100).mul(d.term).div(d.unit==='day'?365:d.unit==='month'?12:1).toFixed(2);});
const depositFilter=ref('all'),depositSort=ref('maturityDate');
const shownDeposits=computed(()=>deposits.value.filter(d=>(!accountId.value||d.accountId===accountId.value)&&(depositFilter.value==='closed'?d.closed:!d.closed&&(depositFilter.value==='all'||(depositFilter.value==='pending'?d.maturityDate>today.value:d.maturityDate<=today.value)))).sort((a,b)=>['principal','annualRate','expectedInterest'].includes(depositSort.value)?new LedgerDecimal(b[depositSort.value as 'principal']).cmp(a[depositSort.value as 'principal']):a[depositSort.value as 'maturityDate'].localeCompare(b[depositSort.value as 'maturityDate'])));
function depositTotal(field:'principal'|'expectedInterest'|'receivedInterest'){return decimalSum(deposits.value.filter(d=>(accountId.value?d.accountId===accountId.value:d.currency==='CNY')&&(field==='receivedInterest'||!d.closed&&d.maturityDate>today.value)).map(d=>d[field]||'0'));}
async function saveDeposit(){if(!editing.value)return;busy.value=true;error.value='';try{await assetTools.saveDeposit(editing.value);await assetTools.syncDeposits();useTransactionsStore().updateStoreInvalidState({accountList:true,transactionList:true,overview:true,statistics:true});editing.value=null;await load();await updateNativeReminders(preferences.preferences,accountStore.allAccountsMap,scope.timeZone);}catch(e){error.value=investmentError(e);}finally{busy.value=false;}}
function closeDeposit(d:FixedDeposit){f7.dialog.confirm(d.settled?'归档保留已入账收益，不修改账户余额。':'提前终止将取消到期自动收益与通知，不修改本金余额。','确认定存操作',()=>{void(async()=>{busy.value=true;try{await assetTools.closeDeposit(d.id);await load();await updateNativeReminders(preferences.preferences,accountStore.allAccountsMap,scope.timeZone);}catch(e){error.value=investmentError(e);}finally{busy.value=false;}})();});}
const live=computed(()=>items.value.filter(a=>!a.excluded));
const liabilities=computed(()=>live.value.filter(a=>a.value!=null&&new LedgerDecimal(a.value).lt(0)));
const distribution=computed(()=>[{name:'流动资产',categories:[1,2,4,8],kind:''},{name:'理财资产',categories:[7,9],kind:''},{name:'二手资产',categories:[7],kind:'secondhand'},{name:'应收款',categories:[6],kind:''}].map(g=>{const selected=live.value.filter(a=>g.categories.includes(a.category)&&(g.kind?a.kind===g.kind:a.kind!=='secondhand')&&a.value!=null&&new LedgerDecimal(a.value).gt(0));return {...g,items:selected,value:decimalSum(selected.map(a=>a.value))};}).filter(g=>g.items.length));
function flowWidth(value:string|null){const max=LedgerDecimal.max(1,...live.value.filter(a=>a.value!=null).map(a=>new LedgerDecimal(a.value!).abs()));return new LedgerDecimal(value||0).abs().div(max).mul(32).plus(2).toNumber();}
function convertedDue(d:CalendarEvent):string|null{const a=items.value.find(a=>!a.portfolio&&a.id===d.accountId);if(d.currency==='CNY')return d.amount;if(!a||a.value==null||a.balance==null||new LedgerDecimal(a.balance).isZero())return null;return new LedgerDecimal(d.amount).mul(new LedgerDecimal(a.value).div(a.balance)).toString();}
function monthRepayment(remaining:boolean){return decimalSum(monthDue.value.filter(d=>d.kind==='repayment'&&!d.id.startsWith('annual:')&&(!remaining||!d.completed)).map(convertedDue));}
const availableCash=computed(()=>{const cash=live.value.filter(a=>!a.portfolio&&[1,2,4,8].includes(a.category)&&a.balance!=null&&new LedgerDecimal(a.balance).gt(0));return decimalSum(cash.map(a=>{if(a.value==null)return null;const held=decimalSum(deposits.value.filter(d=>d.accountId===a.id&&!d.closed&&d.startDate<=today.value&&d.maturityDate>today.value).map(d=>d.principal))||'0';const remaining=LedgerDecimal.max(0,new LedgerDecimal(a.balance!).minus(held));return remaining.mul(new LedgerDecimal(a.value).div(a.balance!)).toString();}));});
</script>
<style scoped>
.cy-asset-tools :deep(.page-content){padding-bottom:32px}h2{font-size:18px;margin:0 0 20px}.hint{font-size:12px;line-height:1.7;color:var(--cy-muted);margin:16px 0}.field{display:flex;align-items:center;gap:14px;margin:18px 0;font-size:14px}.field input,.field select{min-width:0;flex:1;width:100%;border:1px solid var(--cy-line);border-radius:9px;padding:12px;background:var(--cy-card);color:inherit;font:inherit}.choice{display:flex;align-items:center;gap:14px;min-height:60px;border-bottom:1px solid var(--cy-line);font-size:14px}.choice span{flex:1}.choice small{color:var(--cy-muted)}input[type=checkbox]{width:21px;height:21px;accent-color:var(--cy-accent)}.primary,.secondary{padding:14px;border-radius:11px;font:inherit;font-size:14px;min-height:46px}.primary{background:var(--cy-accent);color:white;border:0;margin-top:20px;width:100%}.secondary{background:var(--cy-card);border:1px solid var(--cy-line);color:var(--cy-accent);margin-top:16px}.primary:disabled,.secondary:disabled{opacity:.5}.tool-search{display:flex;align-items:center;gap:14px;border:1px solid var(--cy-line);border-radius:14px;padding:14px;margin-bottom:20px;background:var(--cy-card)}.tool-search .icon{flex:0 0 28px}.tool-search input{flex:1;min-width:0;background:transparent;border:0;color:inherit;font:inherit}.tool-search button{border:0;color:var(--cy-accent);background:none}.tool-account-list>a,.data-row{display:flex;align-items:center;justify-content:space-between;gap:14px;min-height:55px;border-bottom:1px solid var(--cy-line);color:inherit;font-size:14px}.data-row:last-child{border:0}.tool-account-list small,.data-row small{display:block;font-size:11px;color:var(--cy-muted);margin-top:6px}.tool-account-list strong{text-align:right}.form-actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.form-actions .primary{flex:1;width:auto}.form-actions a{margin-top:16px;color:var(--cy-accent)}.deposit-overview{display:grid;grid-template-columns:1fr 1fr;gap:16px}.deposit-overview div{display:flex;flex-direction:column;gap:10px}.deposit-overview span{font-size:12px;color:var(--cy-muted)}.deposit-overview strong{font-size:23px}.deposit-overview small{grid-column:span 2;font-size:11px;color:var(--cy-muted)}.deposit-filters{display:flex;gap:12px;margin:20px 0}.deposit-filters select{flex:1;min-width:0;background:var(--cy-card);color:inherit;border:1px solid var(--cy-line);border-radius:10px;padding:12px}.flow-head{display:flex;justify-content:space-between;gap:8px;font-size:11px;color:var(--cy-muted)}.asset-flow{width:100%;height:auto;margin-top:20px}.asset-flow text{font-size:10px;fill:var(--cy-ink)}.more-data h2{text-align:center}.more-data .data-row{font-size:15px;min-height:64px}
.cy-asset-tools .cy-panel{border:0;border-radius:12px;padding:16px}.deposit-fields{padding:0 16px!important}.deposit-fields label,.deposit-fields>div{display:flex;justify-content:space-between;align-items:center;gap:14px;min-height:53px;font-size:15px}.deposit-fields input,.deposit-fields select{min-width:0;flex:1;width:60%;text-align:right;background:none;border:0;color:var(--cy-ink);font:inherit}.deposit-fields input::placeholder{color:var(--cy-muted)}.deposit-fields .deposit-unit{flex:0 0 44px;width:44px}.deposit-fields strong{font-weight:400}.deposit-overview{grid-template-columns:repeat(3,minmax(0,1fr));text-align:center;gap:8px}.deposit-overview strong{font-size:19px}.deposit-overview small{grid-column:span 3}.deposit-record h2{font-size:15px;font-weight:500}.deposit-record .cy-section-head>span{font-size:12px;color:var(--cy-muted)}.deposit-record .form-actions .secondary{margin:0;padding:8px 12px;min-height:34px}
</style>
