<template>
 <f7-page class="cy-mobile-surface cy-investment-page" @page:afterin="refresh">
  <f7-navbar title="理财统计" back-link="理财" />
  <main class="inv-body">
   <p v-if="error" class="cy-message" role="alert">{{ error }}</p>
   <div class="inv-period"><input v-model="from" type="date" aria-label="统计开始日期" /><span>—</span><input v-model="to" type="date" aria-label="统计结束日期" /></div>
   <section class="inv-card"><dl class="inv-metrics"><div v-for="m in flowMetrics" :key="m.key"><dt>{{ m.name }}</dt><dd><button class="inv-link" style="color:inherit;padding:0" @click="metric=m.key">{{ money(m.value) }}</button></dd></div></dl></section>
   <section class="inv-card"><dl class="inv-metrics"><div><dt>已实现盈亏（区间）</dt><dd :class="profitClass(realized)">{{ money(realized) }}</dd></div><div><dt>手续费（区间）</dt><dd>{{ money(fees) }}</dd></div><div><dt>计入净资产金额</dt><dd>{{ money(netValue) }}</dd></div><div><dt>当前市值</dt><dd>{{ money(value) }}</dd></div><div><dt>持有收益</dt><dd :class="profitClass(holdingProfit)">{{ money(holdingProfit) }}</dd></div><div><dt>累计收益</dt><dd :class="profitClass(totalProfit)">{{ money(totalProfit) }}</dd></div><div><dt>累计年化估算</dt><dd>{{ !assetAmountsVisible?'••••':report?.annualized==null||monetaryRows.length?'—':new LedgerDecimal(report.annualized).toFixed(2)+'%' }}</dd></div></dl><details class="inv-details" style="margin-top:16px"><summary>统计口径</summary><p>买入包含手续费，卖出扣除手续费，统一按交易时的历史汇率折合人民币。市值与持有收益为当前值；累计收益包含已标记的显示修正。隐藏不影响汇总；账户、持仓的生效账本与“计入总资产”设置和理财列表一致。关闭“盈亏计入总资产”时，计入净资产金额使用成本，当前市值仍是市场估值。</p><p>年化按不含显示修正的累计收益和实际资金占用天数估算，不是基金价格涨幅。存在持仓校准、转移、未知成本或缺失行情时不计算。统计区间不改变当前持仓。</p><p v-if="monetaryRows.length">当前市值和累计收益包含货币基金；买卖统计、年化和历史走势只计算投资持仓，货币基金逐日收益可进入资金账户查看。</p></details></section>
   <section class="inv-card"><div class="inv-event-line"><h2>资金流向</h2><span class="inv-muted">买入 / 卖出</span></div><p v-if="!flows.length" class="cy-empty">区间内没有买卖记录</p><div v-for="item in flows" :key="item.month" class="flow-row"><small>{{ item.month }}</small><div><span class="flow-bar flow-buy" :style="{width:item.buyWidth+'%'}" /><span class="flow-bar flow-sell" :style="{width:item.sellWidth+'%'}" /></div><span>{{ money(item.buy) }}<br /><small class="inv-muted">{{ money(item.sell) }}</small></span></div></section>
   <section class="inv-card"><h2>累计收益走势</h2><p class="inv-muted">按已保存估值，不含显示修正</p><p v-if="!assetAmountsVisible" class="cy-empty">金额已隐藏</p><template v-else-if="plot.count>1"><svg class="inv-chart" viewBox="0 0 340 150" role="img" aria-label="已保存估值的累计收益，缺失数据处留空"><path d="M5 139H335" stroke="var(--cy-line)" /><polyline v-for="(segment,index) in plot.segments" :key="index" :points="segment" fill="none" stroke="var(--cy-accent)" stroke-width="2" stroke-linejoin="round" /></svg><div class="inv-chart-labels"><span>{{ plot.first }}</span><span>{{ plot.last }}</span></div></template><p v-else class="cy-empty">积累两条实际估值后显示走势</p></section>
   <section class="inv-card"><h2>理财明细</h2><f7-link v-for="r in detailRows" :key="r.key" class="inv-event" :href="`/investments/position?accountId=${r.position.accountId}&instrumentId=${encodeURIComponent(r.position.instrumentId)}`"><div class="inv-event-line"><strong>{{ r.name }}</strong><strong>{{ money(r.position.marketValue) }}</strong></div><div class="inv-event-line"><small>{{ r.group }}</small><small :class="profitClass(r.profit)">累计收益 {{ money(r.profit) }}</small></div></f7-link><f7-link v-for="r in monetaryRows.filter(r=>!r.hidden)" :key="r.id" class="inv-event" :href="`/account/detail?id=${r.id}`"><div class="inv-event-line"><strong>{{ r.binding.name }}</strong><strong>{{ money(r.value) }}</strong></div><div class="inv-event-line"><small>货币基金</small><small>已记录收益 {{ money(r.binding.totalIncome) }}</small></div></f7-link></section>
  </main>
  <f7-sheet class="inv-sheet cy-mobile-surface cy-investment-page" :opened="!!metric" @sheet:closed="metric=''" swipe-to-close backdrop><h2>{{ flowMetrics.find(m=>m.key===metric)?.name }}</h2><p v-if="!metricItems.length" class="cy-empty">没有对应交易</p><f7-link v-for="item in metricItems" :key="item.event.id" class="inv-event" :href="`/investments/record?action=revise&eventId=${item.event.id}&accountId=${item.event.accountId}&instrumentId=${encodeURIComponent(item.event.instrumentId)}`" sheet-close><div class="inv-event-line"><strong>{{ investmentNames[item.event.type] }} · {{ assets.find(a=>a.id===item.event.instrumentId)?.name }}</strong><strong>{{ money(tradeCash(item.event)) }}</strong></div><small class="inv-muted">{{ moment.unix(item.event.occurredAt).tz(zone).format('YYYY-MM-DD') }}</small></f7-link></f7-sheet>
 </f7-page>
</template>
<script setup lang="ts">
import {computed,ref} from 'vue';
import type {Router} from 'framework7/types';
import moment from 'moment-timezone';
import {investments,investmentError} from '@/lib/investments.ts';
import {useInvestmentData,investmentSum,profitClass,investmentNames} from '@/lib/investment-mobile.ts';
import {LedgerDecimal} from '@/lib/ledger-display.ts';
import {assetMoney as money,assetAmountsVisible} from '@/lib/asset-visibility.ts';
import {holdingVisible,investmentAmounts} from '@/lib/investment-scope.ts';
import type {InvestmentEvent,InvestmentReport} from '@/models/investment.ts';
const props=defineProps<{f7route:Router.Route}>(),q=props.f7route.query;
const {includedRows,assets,monetaryRows:allMonetary,books,preferences,error,summaryReady,zone,load}=useInvestmentData(),report=ref<InvestmentReport>(),metric=ref('');
const from=ref(moment().startOf('year').format('YYYY-MM-DD')),to=ref(moment().format('YYYY-MM-DD'));
const scopedRows=computed(()=>includedRows.value.filter(r=>(!q['accountId']||r.position.accountId===q['accountId'])&&(!q['instrumentId']||r.position.instrumentId===q['instrumentId'])));
const detailRows=computed(()=>scopedRows.value.filter(r=>holdingVisible(r.profile,preferences.preferences)));
const monetaryRows=computed(()=>q['accountId']||q['instrumentId']?[]:allMonetary.value.filter(r=>!r.excluded));
const amounts=computed(()=>summaryReady.value?investmentAmounts(scopedRows.value,monetaryRows.value):undefined);
const netValue=computed(()=>amounts.value?.netValue),value=computed(()=>amounts.value?.marketValue),holdingProfit=computed(()=>amounts.value?.holdingProfit),totalProfit=computed(()=>amounts.value?.totalProfit);
const items=computed(()=>report.value?.items.filter(item=>{const date=moment.unix(item.event.occurredAt).tz(zone.value).format('YYYY-MM-DD');return date>=from.value&&date<=to.value;})||[]);
function primary(e:InvestmentEvent):boolean{return (!q['accountId']||q['accountId']===e.accountId)&&(!q['instrumentId']||q['instrumentId']===e.instrumentId);}
function tradeCash(e:InvestmentEvent):string|null{if(!e.exchangeRate)return null;const amount=new LedgerDecimal(e.amount),fee=new LedgerDecimal(e.fee);return (e.type==='BUY'?amount.plus(fee):amount.minus(fee)).mul(e.exchangeRate).toString();}
const buys=computed(()=>!report.value?null:investmentSum(items.value.filter(i=>i.event.type==='BUY'&&primary(i.event)).map(i=>tradeCash(i.event)))),sells=computed(()=>!report.value?null:investmentSum(items.value.filter(i=>i.event.type==='SELL'&&primary(i.event)).map(i=>tradeCash(i.event))));
const realized=computed(()=>!report.value?null:investmentSum(items.value.map(i=>i.effect.realizedPnl))),fees=computed(()=>!report.value?null:investmentSum(items.value.filter(i=>['BUY','SELL','TRANSFER'].includes(i.event.type)).map(i=>i.effect.investmentFee)));
const flowMetrics=computed(()=>[{key:'BUY',name:'买入（元）',value:buys.value},{key:'SELL',name:'卖出（元）',value:sells.value},{key:'net',name:'净投入（元）',value:buys.value==null||sells.value==null?null:new LedgerDecimal(buys.value).minus(sells.value).toString()}]);
const metricItems=computed(()=>items.value.filter(i=>metric.value==='net'?['BUY','SELL'].includes(i.event.type):i.event.type===metric.value));
const flows=computed(()=>{const groups=new Map<string,{buy:(string|null)[];sell:(string|null)[]}>();for(const i of items.value){if(!['BUY','SELL'].includes(i.event.type)||!primary(i.event))continue;const month=moment.unix(i.event.occurredAt).tz(zone.value).format('YYYY-MM'),g=groups.get(month)||{buy:[],sell:[]};(i.event.type==='BUY'&&primary(i.event)?g.buy:g.sell).push(tradeCash(i.event));groups.set(month,g);}const data=[...groups].sort(([a],[b])=>a.localeCompare(b)).map(([month,g])=>({month,buy:investmentSum(g.buy),sell:investmentSum(g.sell)})),max=data.reduce((m,d)=>LedgerDecimal.max(m,d.buy||0,d.sell||0),new LedgerDecimal(1));return data.map(d=>({...d,buyWidth:d.buy==null?0:new LedgerDecimal(d.buy).div(max).mul(100).toNumber(),sellWidth:d.sell==null?0:new LedgerDecimal(d.sell).div(max).mul(100).toNumber()}));});
const plot=computed(()=>{const points=(report.value?.history||[]).filter(p=>{const d=moment.unix(p.at).tz(zone.value).format('YYYY-MM-DD');return d>=from.value&&d<=to.value;}),valid=points.filter(p=>p.profit!=null);if(valid.length<2)return {count:valid.length,segments:[],first:'',last:''};const min=LedgerDecimal.min(...valid.map(p=>p.profit!)),max=LedgerDecimal.max(...valid.map(p=>p.profit!)),range=max.minus(min).isZero()?new LedgerDecimal(1):max.minus(min),first=points[0]!.at,last=points.at(-1)!.at,segments:string[]=[];let current:string[]=[];for(const p of points){if(p.profit==null){if(current.length)segments.push(current.join(' '));current=[];continue;}current.push(`${5+(p.at-first)/Math.max(1,last-first)*330},${139-new LedgerDecimal(p.profit).minus(min).div(range).mul(124).toNumber()}`);}if(current.length)segments.push(current.join(' '));return {count:valid.length,segments,first:moment.unix(first).tz(zone.value).format('YYYY-MM-DD'),last:moment.unix(last).tz(zone.value).format('YYYY-MM-DD')};});
async function refresh():Promise<void>{report.value=undefined;await load();try{report.value=await investments.report(q['accountId']||'',q['instrumentId']||'',books.selectedBookIds);}catch(e){error.value=investmentError(e);}}
</script>
<style scoped>
.flow-row{display:grid;grid-template-columns:58px 1fr auto;align-items:center;gap:12px;padding:14px 0;font-size:12px}.flow-row>span{text-align:right;line-height:1.8}.flow-bar{display:block;height:5px;min-width:1px;border-radius:3px}.flow-buy{background:#e75b5b;margin-bottom:7px}.flow-sell{background:#239777}
</style>
