<template><f7-page class="cy-mobile-surface" @page:afterin="load"><f7-navbar title="分类关键词" back-link="返回"><f7-nav-right><f7-link @click="edit()">添加</f7-link></f7-nav-right></f7-navbar><main class="cy-page-body"><p class="cy-helper">导入账单时，按备注中的关键词匹配分类。确认预览后才会入账。</p><p v-if="error" class="cy-message">{{ error }}</p><p v-if="!rules.length" class="cy-empty">暂无关键词规则</p><section v-for="rule in rules" :key="rule.id" class="cy-panel cy-keyword-row"><button @click="edit(rule)"><strong>{{ categoryMap[rule.data.categoryId]?.name || '分类已删除' }}</strong><p>{{ rule.data.keywords.join('、') }}</p><small>{{ rule.data.enabled?'已启用':'已停用' }}{{ rule.data.accountId?` · ${accountMap[rule.data.accountId]?.name || '账户已删除'}`:'' }}</small></button><f7-toggle :checked="rule.data.enabled" :disabled="busy" @toggle:change="toggle(rule,$event)" /></section></main><f7-popup v-model:opened="opened" class="cy-mobile-surface"><f7-page><f7-navbar :title="draft.id?'编辑关键词':'添加关键词'"><f7-nav-left><f7-link popup-close>取消</f7-link></f7-nav-left><f7-nav-right><f7-link :class="{disabled:busy}" @click="save">保存</f7-link></f7-nav-right></f7-navbar><main class="cy-page-body"><p v-if="editError" class="cy-message">{{ editError }}</p><f7-list strong inset><f7-list-input label="关键词" type="textarea" placeholder="多个关键词用逗号或换行分隔" v-model:value="words" /><f7-list-input label="分类" type="select" v-model:value="draft.data.categoryId"><option value="">请选择分类</option><option v-for="c in Object.values(categoryMap).filter(c=>c.parentId!=='0')" :key="c.id" :value="c.id">{{ c.name }}</option></f7-list-input><f7-list-input label="默认账户" type="select" v-model:value="draft.data.accountId"><option value="">按导入设置</option><option v-for="a in Object.values(accountMap).filter(a=>!a.subAccounts?.length)" :key="a.id" :value="a.id">{{ a.name }}</option></f7-list-input></f7-list><section class="cy-panel"><h3>附加标签</h3><label v-for="t in Object.values(tags.allTransactionTagsMap)" :key="t.id" class="cy-keyword-tag"><input v-model="draft.data.tagIds" type="checkbox" :value="t.id" />{{ t.name }}</label></section><button v-if="draft.id" class="cy-button cy-danger" :disabled="busy" @click="remove">删除规则</button></main></f7-page></f7-popup></f7-page></template>
<script setup lang="ts">
import {computed,ref} from 'vue';
import {ledgerWorkspace,type LedgerWorkspaceItem,type LedgerKeyword} from '@/lib/ledger-workspace.ts';
import {useMobileLedger} from '@/lib/mobile-ledger.ts';
import {useTransactionCategoriesStore} from '@/stores/transactionCategory.ts';
import {useAccountsStore} from '@/stores/account.ts';
import {useTransactionTagsStore} from '@/stores/transactionTag.ts';
import {investmentError} from '@/lib/investments.ts';
import {useI18nUIComponents} from '@/lib/ui/mobile.ts';
const categories=useTransactionCategoriesStore(),accounts=useAccountsStore(),tags=useTransactionTagsStore(),ledger=useMobileLedger({bookIds:()=>[],applyFilters:()=>false}),{showConfirm}=useI18nUIComponents(),categoryMap=computed(()=>categories.allTransactionCategoriesMap),accountMap=computed(()=>accounts.allAccountsMap);
const blank=():LedgerWorkspaceItem<LedgerKeyword>=>({id:'',kind:'keyword',revision:'0',data:{keywords:[],categoryId:'',accountId:'',tagIds:[],enabled:true}});
const rules=ref<LedgerWorkspaceItem<LedgerKeyword>[]>([]),draft=ref(blank()),words=ref(''),opened=ref(false),busy=ref(false),error=ref(''),editError=ref('');
async function load(){error.value='';try{await ledger.load(0,1);rules.value=await ledgerWorkspace.keywords();}catch(e){error.value=investmentError(e);}}
function edit(rule?:LedgerWorkspaceItem<LedgerKeyword>){draft.value=rule?JSON.parse(JSON.stringify(rule)):blank();words.value=draft.value.data.keywords.join('\n');editError.value='';opened.value=true;}
async function persist(rule:LedgerWorkspaceItem<LedgerKeyword>){const result=await ledgerWorkspace.save(rule);rules.value=[result,...rules.value.filter(r=>r.id!==result.id)];}
async function save(){if(busy.value)return;busy.value=true;editError.value='';try{draft.value.data.keywords=[...new Set(words.value.split(/[,，\n]+/).map(w=>w.trim()).filter(Boolean))];await persist(draft.value);opened.value=false;}catch(e){editError.value=investmentError(e);}finally{busy.value=false;}}
async function toggle(rule:LedgerWorkspaceItem<LedgerKeyword>,enabled:boolean){busy.value=true;try{await persist({...rule,data:{...rule.data,enabled}});}catch(e){error.value=investmentError(e);}finally{busy.value=false;}}
function remove(){showConfirm('删除这条关键词规则？',async()=>{busy.value=true;try{await ledgerWorkspace.delete(draft.value);rules.value=rules.value.filter(r=>r.id!==draft.value.id);opened.value=false;}catch(e){editError.value=investmentError(e);}finally{busy.value=false;}});}
</script>
<style scoped>.cy-helper{font-size:12px;color:var(--cy-muted);line-height:1.7}.cy-keyword-row{display:flex;align-items:center;gap:15px}.cy-keyword-row>button{flex:1;background:none;border:0;color:var(--cy-ink);text-align:left;padding:0}.cy-keyword-row strong{font-size:16px}.cy-keyword-row p{font-size:14px;line-height:1.6;margin:12px 0}.cy-keyword-row small{font-size:11px;color:var(--cy-muted)}.cy-keyword-tag{display:inline-flex;align-items:center;gap:6px;margin:12px 14px 0 0;font-size:13px}.cy-danger{color:var(--cy-expense)}</style>
