<template>
 <f7-page class="cy-mobile-surface cy-reimbursement-page" ptr @ptr:refresh="load" @page:afterin="load">
  <f7-navbar :title="account?.name||'报销'" back-link="资产"><f7-nav-right><AccountOptionsMenu v-if="account" :edit-href="`/account/edit?id=${account.id}`" :target="{id:account.id,name:account.name,kind:'cash',href:`/assets/reimbursements?id=${account.id}`}" @deleted="f7router.back()"/></f7-nav-right></f7-navbar>
  <main class="cy-page-body">
   <p v-if="error" class="cy-message" role="alert">{{error}}</p>
   <section class="reimbursement-summary"><div v-for="total in totals" :key="total.currency" class="cy-panel"><span>{{total.currency}} 可报销<strong>{{ledgerMoney(total.pending,false)}}</strong></span><span>已报销<strong>{{ledgerMoney(total.paid,false)}}</strong></span></div></section>
   <section v-if="!id" class="reimbursement-accounts cy-panel"><f7-link v-for="a in reimbursementAccounts" :key="a.id" :href="`/assets/reimbursements?id=${a.id}`"><item-icon icon-type="account" :icon-id="a.icon" :color="a.color"/><span>{{a.name}}</span><strong>{{a.currency}} {{ledgerMoney(new LedgerDecimal(a.balance).div(100).toString(),false)}}</strong></f7-link><p v-if="!reimbursementAccounts.length" class="cy-empty">还没有报销账户</p><f7-link class="reimbursement-add-account" href="/account/add?preset=reimbursement">添加报销账户</f7-link></section>
   <template v-else>
   <nav class="reimbursement-tabs"><button v-for="tab in tabs" :key="tab.id" :aria-pressed="status===tab.id" @click="status=tab.id">{{tab.name}}<small>{{count(tab.id)}}</small></button></nav>
   <p v-if="loading&&!claims.length" class="cy-empty">正在读取报销账单…</p>
   <p v-else-if="!filtered.length" class="cy-empty">{{status==='done'?'还没有已报销账单':'暂无待报销账单'}}<br/><f7-link v-if="!reimbursementAccounts.length" href="/account/add?preset=reimbursement">添加报销账户</f7-link></p>
   <section class="cy-panel reimbursement-list" v-if="filtered.length"><button v-for="claim in filtered" :key="claim.transactionId" class="reimbursement-row" @click="select(claim)"><item-icon icon-type="category" :icon-id="categories.allTransactionCategoriesMap[claim.categoryId]?.icon||'1'"/><span>{{claim.comment||categories.allTransactionCategoriesMap[claim.categoryId]?.name||'报销支出'}}<small>{{date(claim.time)}} · {{accounts.allAccountsMap[claim.sourceAccountId]?.name||'支出账户'}}</small></span><span class="reimbursement-amount">{{ledgerMoney(claim.amount,false)}}<small>{{claim.ended?'已结束':claim.closed?'已报销':`待报 ${ledgerMoney(claim.pending,false)}`}}</small></span></button></section>
   </template>
  </main>
  <template #fixed><f7-link class="cy-fab" aria-label="新增报销" @click="add"><f7-icon f7="plus"/></f7-link></template>
  <f7-sheet v-model:opened="showAccountPicker" class="cy-mobile-surface reimbursement-sheet" backdrop><div class="sheet-heading"><strong>选择报销账户</strong><f7-link sheet-close>取消</f7-link></div><f7-list><f7-list-item v-for="a in reimbursementAccounts" :key="a.id" :title="a.name" :link="addLink(a.id)" sheet-close/><f7-list-item title="添加报销账户" link="/account/add?preset=reimbursement" sheet-close/></f7-list></f7-sheet>
  <f7-sheet v-model:opened="showDetail" class="cy-mobile-surface reimbursement-sheet" backdrop swipe-to-close>
   <template v-if="selected"><div class="sheet-heading"><strong>报销详情</strong><f7-link sheet-close>关闭</f7-link></div><div class="sheet-body"><div class="reimbursement-detail-amount">{{selected.currency}} {{ledgerMoney(selected.amount,false)}}<small>{{selected.comment||categories.allTransactionCategoriesMap[selected.categoryId]?.name}}</small></div><div class="detail-pair"><span>待报销</span><strong>{{ledgerMoney(selected.ended?'0':selected.pending,false)}}</strong></div><div class="detail-pair"><span>已报销</span><strong>{{ledgerMoney(selected.paid,false)}}</strong></div><h3>到账记录</h3><p v-if="!selected.receipts.length" class="cy-muted">尚无到账记录</p><f7-link v-for="receipt in selected.receipts" :key="receipt.id" class="detail-pair" :href="`/transaction/detail?id=${receipt.transactionId}`" sheet-close><span>{{accounts.allAccountsMap[receipt.accountId]?.name}}<small>{{date(receipt.time)}}</small></span><strong>＋{{ledgerMoney(receipt.amount,false)}}</strong></f7-link><button v-if="!selected.closed" class="primary" @click="openReceive">报销到账</button><div class="reimbursement-actions"><f7-link :href="`/transaction/edit?id=${selected.transactionId}`" sheet-close>编辑支出</f7-link><button v-if="!selected.ended&&!selected.closed" @click="changeState('end')">结束报销</button><button v-if="selected.ended" @click="changeState('reopen')">恢复报销</button><button v-if="new LedgerDecimal(selected.paid).isZero()" @click="changeState('unassign')">取消报销</button></div></div></template>
  </f7-sheet>
  <f7-popup v-model:opened="showReceive" class="cy-mobile-surface"><f7-page class="cy-mobile-surface cy-reimbursement-page"><f7-navbar title="报销到账"><f7-nav-left><f7-link icon-f7="xmark" :disabled="busy" @click="showReceive=false"/></f7-nav-left><f7-nav-right><f7-link icon-f7="checkmark" aria-label="保存报销到账" :disabled="busy" @click="receive"/></f7-nav-right></f7-navbar><main class="cy-page-body"><p v-if="receiveError" class="cy-message" role="alert">{{receiveError}}</p><section class="cy-panel receipt-form"><label>到账金额<input v-model="receiptAmount" inputmode="decimal" aria-label="到账金额" maxlength="16"/></label><label>到账账户<select v-model="receiptAccount" aria-label="到账账户"><option disabled value="">请选择账户</option><option v-for="a in cashAccounts" :key="a.id" :value="a.id">{{a.name}}</option></select></label><label>到账日期<input v-model="receiptDate" type="date" aria-label="到账日期" :min="selected?moment.unix(selected.time).tz(scope.timeZone).format('YYYY-MM-DD'):undefined"/></label><label>备注<input v-model="receiptComment" placeholder="选填" maxlength="200" aria-label="到账备注"/></label></section><p class="cy-muted">到账只恢复现金余额，不计入收入。</p></main></f7-page></f7-popup>
 </f7-page>
</template>
<script setup lang="ts">
import {assetMoney as ledgerMoney} from '@/lib/asset-visibility.ts';
import {computed,ref} from 'vue';
import {f7} from 'framework7-vue';
import type {Router} from 'framework7/types';
import moment from 'moment-timezone';
import {reimbursements,type ReimbursementClaim} from '@/lib/reimbursements.ts';
import {investmentError} from '@/lib/investments.ts';
import {LedgerDecimal,keepUpToDate} from '@/lib/mobile-ledger.ts';
import {generateRandomUUID} from '@/lib/misc.ts';
import {useAccountsStore} from '@/stores/account.ts';
import {useBooksStore} from '@/stores/books.ts';
import {useTransactionCategoriesStore} from '@/stores/transactionCategory.ts';
import {useLedgerScopeStore} from '@/stores/ledgerScope.ts';
import AccountOptionsMenu from '@/components/mobile/AccountOptionsMenu.vue';
const props=defineProps<{f7route:Router.Route;f7router:Router.Router}>();
const accounts=useAccountsStore(),categories=useTransactionCategoriesStore(),books=useBooksStore(),scope=useLedgerScopeStore();
const id=computed(()=>props.f7route.query['id']||''),account=computed(()=>accounts.allAccountsMap[id.value]);
const reimbursementAccounts=computed(()=>accounts.allVisiblePlainAccounts.filter(a=>a.assetProfile.kind==='reimbursement'));
const claims=ref<ReimbursementClaim[]>([]),selected=ref<ReimbursementClaim>(),loading=ref(false),busy=ref(false),error=ref(''),receiveError=ref('');
const tabs=[{id:'pending',name:'待报销'},{id:'partial',name:'部分报销'},{id:'done',name:'已报销'}] as const;
type Status=typeof tabs[number]['id'];
const status=ref<Status>('pending'),showAccountPicker=ref(false),showDetail=ref(false),showReceive=ref(false);
const receiptAmount=ref(''),receiptAccount=ref(''),receiptDate=ref(''),receiptComment=ref('');let requestId=generateRandomUUID();
const scopedClaims=computed(()=>claims.value.filter(c=>(!id.value||c.accountId===id.value)&&(!books.selectedBookIds.length||books.selectedBookIds.includes(c.bookId))));
const matches=(c:ReimbursementClaim,s:Status)=>s==='done'?c.closed:s==='partial'?!c.closed&&new LedgerDecimal(c.paid).gt(0):!c.closed&&new LedgerDecimal(c.paid).isZero();
const filtered=computed(()=>scopedClaims.value.filter(c=>matches(c,status.value)));
const count=(s:Status)=>scopedClaims.value.filter(c=>matches(c,s)).length;
const totals=computed(()=>{const m=new Map<string,{currency:string;pending:InstanceType<typeof LedgerDecimal>;paid:InstanceType<typeof LedgerDecimal>}>();for(const c of scopedClaims.value){const t=m.get(c.currency)||{currency:c.currency,pending:new LedgerDecimal(0),paid:new LedgerDecimal(0)};if(!c.closed)t.pending=t.pending.plus(c.pending);t.paid=t.paid.plus(c.paid);m.set(c.currency,t);}if(!m.size)m.set(account.value?.currency||'CNY',{currency:account.value?.currency||'CNY',pending:new LedgerDecimal(0),paid:new LedgerDecimal(0)});return [...m.values()].map(t=>({...t,pending:t.pending.toString(),paid:t.paid.toString()}));});
const cashAccounts=computed(()=>accounts.allVisiblePlainAccounts.filter(a=>a.assetProfile.kind!=='reimbursement'&&a.currency===selected.value?.currency));
const date=(at:number)=>moment.unix(at).tz(scope.timeZone).format('YYYY年M月D日');
const addLink=(accountId:string)=>`/transaction/add?type=3&reimbursementAccountId=${accountId}&noTransactionDraft=true`;
async function load(done?:()=>void):Promise<void>{loading.value=true;error.value='';try{const [rows]=await Promise.all([reimbursements.list(),accounts.loadAllAccounts({force:true}).catch(keepUpToDate),categories.loadAllCategories({force:false}).catch(keepUpToDate),books.loadBooks()]);claims.value=rows;if(selected.value)selected.value=rows.find(c=>c.transactionId===selected.value!.transactionId);}catch(e){error.value=investmentError(e);}finally{loading.value=false;if(typeof done==='function')done();}}
function add():void{if(!id.value){props.f7router.navigate('/account/add?preset=reimbursement');return;}if(account.value)props.f7router.navigate(addLink(account.value.id));else if(reimbursementAccounts.value.length===1)props.f7router.navigate(addLink(reimbursementAccounts.value[0]!.id));else showAccountPicker.value=true;}
function select(c:ReimbursementClaim):void{selected.value=c;showDetail.value=true;}
function openReceive():void{if(!selected.value)return;receiptAmount.value=selected.value.pending;receiptAccount.value=cashAccounts.value.find(a=>a.id===selected.value?.sourceAccountId)?.id||cashAccounts.value[0]?.id||'';receiptDate.value=moment().tz(scope.timeZone).format('YYYY-MM-DD');receiptComment.value='';requestId=generateRandomUUID();receiveError.value='';showDetail.value=false;showReceive.value=true;}
async function receive():Promise<void>{if(busy.value||!selected.value)return;busy.value=true;receiveError.value='';try{if(!/^(0|[1-9]\d{0,12})(\.\d{1,2})?$/.test(receiptAmount.value))throw Error('请输入最多两位小数的到账金额');const at=moment.tz(receiptDate.value+' 12:00','YYYY-MM-DD HH:mm',true,scope.timeZone);if(!at.isValid())throw Error('请选择有效到账日期');await reimbursements.receive({expenseId:selected.value.transactionId,accountId:receiptAccount.value,amount:receiptAmount.value,time:Math.max(at.unix(),selected.value.time),timeZone:scope.timeZone,comment:receiptComment.value,requestId});showReceive.value=false;await load();}catch(e){receiveError.value=investmentError(e);}finally{busy.value=false;}}
function changeState(action:'end'|'reopen'|'unassign'):void{if(!selected.value||busy.value)return;const message=action==='end'?'结束后，剩余金额不再作为应收资产。':action==='unassign'?'取消报销后，这笔支出恢复计入日常收支。':'恢复剩余可报金额为应收资产。';f7.dialog.confirm(message,'报销',async()=>{busy.value=true;try{await reimbursements.state(selected.value!.transactionId,action);showDetail.value=false;await load();}catch(e){error.value=investmentError(e);}finally{busy.value=false;}});}
</script>
<style scoped>
.reimbursement-accounts{padding:0 16px!important;border:0!important;border-radius:12px!important}.reimbursement-accounts>a{display:flex;align-items:center;gap:14px;min-height:58px;color:var(--cy-ink);font-size:15px}.reimbursement-accounts>a>span{flex:1}.reimbursement-accounts strong{font-weight:400;color:var(--cy-accent)}.reimbursement-accounts .reimbursement-add-account{color:var(--cy-accent);justify-content:center;font-size:14px}

.reimbursement-summary .cy-panel{display:flex;justify-content:space-between;border:0;border-radius:12px;padding:20px}.reimbursement-summary span{font-size:12px;color:var(--cy-muted)}.reimbursement-summary strong{display:block;margin-top:8px;color:var(--cy-accent);font-size:24px;font-weight:500}.reimbursement-tabs{display:flex;border-bottom:1px solid var(--cy-line);margin:6px 0 16px}.reimbursement-tabs button{flex:1;padding:13px 0;background:none;border:0;color:var(--cy-muted);font-size:14px}.reimbursement-tabs button[aria-pressed=true]{color:var(--cy-accent);border-bottom:2px solid var(--cy-accent)}.reimbursement-tabs small{margin-left:4px;font-size:10px}.reimbursement-list{padding:2px 14px!important;border:0!important;border-radius:12px!important}.reimbursement-row{display:flex;align-items:center;gap:12px;padding:16px 0;border:0;background:none;width:100%!important;text-align:left;color:var(--cy-ink)}.reimbursement-row>span{min-width:0;flex:1}.reimbursement-row small,.detail-pair small{display:block;color:var(--cy-muted);font-size:11px;margin-top:6px}.reimbursement-row .reimbursement-amount{flex:0 0 auto;text-align:right}.reimbursement-sheet{height:auto;max-height:85dvh;background:var(--cy-bg);border-radius:18px 18px 0 0;overflow:auto}.sheet-heading{display:flex;align-items:center;justify-content:space-between;padding:18px}.sheet-body{padding:0 18px 30px}.reimbursement-detail-amount{text-align:center;font-size:27px;padding:16px 0 24px}.reimbursement-detail-amount small{display:block;font-size:14px;color:var(--cy-muted);margin-top:12px}.detail-pair{display:flex;justify-content:space-between;align-items:center;padding:12px 0;color:var(--cy-ink)}.detail-pair strong{font-weight:400;color:var(--cy-accent)}.sheet-body h3{font-size:14px;font-weight:400;color:var(--cy-muted);margin:20px 0 8px}.primary{background:var(--cy-accent);color:var(--cy-bg);width:100%!important;border:0;border-radius:10px;padding:14px;margin-top:20px}.reimbursement-actions{display:flex;justify-content:space-around;margin-top:20px;gap:12px;font-size:13px}.reimbursement-actions button{border:0;background:none;color:var(--cy-muted)}.receipt-form{border:0!important;border-radius:12px!important;padding:0 16px!important}.receipt-form label{min-height:53px;display:flex;justify-content:space-between;align-items:center;gap:20px;font-size:15px}.receipt-form input,.receipt-form select{width:65%;min-width:0;text-align:right;background:none;border:0;color:var(--cy-ink)}.cy-reimbursement-page .cy-fab{bottom:28px}
</style>
