<template><f7-page class="cy-main-page cy-mobile-surface" @page:afterin="load"><main class="cy-page-body cy-mine-body"><button class="cy-mine-profile" @click="openProfile"><img v-if="user.currentUserAvatar" :src="user.currentUserAvatar" alt="头像" /><span v-else class="cy-mine-avatar"><f7-icon f7="person_fill" /></span><div><h1>{{ user.currentUserNickname || '我的账本' }}</h1><p>已记账 {{ recordedDays ?? '—' }} 天 <span>›</span></p></div></button><p v-if="error" class="cy-message">{{ error }}</p>
<nav class="cy-panel cy-mine-grid" aria-label="常用管理"><f7-link href="/schedule/list"><f7-icon f7="calendar_badge_plus" />周期记账</f7-link><f7-link href="/wishes"><f7-icon f7="gift" />愿望清单</f7-link><f7-link href="/keywords"><f7-icon f7="text_badge_checkmark" />分类关键词</f7-link><f7-link href="/books"><f7-icon f7="book_closed" />账本管理</f7-link><f7-link href="/tag/list"><f7-icon f7="tag" />标签管理</f7-link><f7-link href="/category/all"><f7-icon f7="square_grid_2x2" />分类管理</f7-link></nav>
<section class="cy-panel cy-mine-links cy-mine-more" aria-label="更多设置"><f7-link href="/settings/more"><f7-icon f7="gear_alt" /><span>更多设置</span><f7-icon f7="chevron_right" /></f7-link></section>
<section class="cy-panel cy-mine-links"><h2>数据管理</h2><f7-link href="/user/backup"><f7-icon f7="archivebox" /><span>数据备份</span><f7-icon f7="chevron_right" /></f7-link><f7-link href="/user/data/management"><f7-icon f7="arrow_up_arrow_down" /><span>导入导出</span><f7-icon f7="chevron_right" /></f7-link><f7-link href="/transaction/list?view=pictures"><f7-icon f7="photo_on_rectangle" /><span>账单图片</span><f7-icon f7="chevron_right" /></f7-link></section><section class="cy-panel cy-mine-links"><h2>其他</h2><f7-link href="/settings/appearance"><f7-icon f7="paintbrush" /><span>主题外观</span><f7-icon f7="chevron_right" /></f7-link></section></main><template #fixed><LedgerNavigation active="settings" /></template>
<f7-popup v-model:opened="profileOpen" class="cy-mobile-surface"><f7-page><f7-navbar title="个人资料"><f7-nav-left><f7-link popup-close>取消</f7-link></f7-nav-left><f7-nav-right><f7-link :class="{disabled:busy}" @click="saveProfile">保存</f7-link></f7-nav-right></f7-navbar><main class="cy-page-body"><section class="cy-panel cy-profile-form"><label>头像<input type="file" accept="image/*" :disabled="busy" @change="avatar" /></label><label>昵称<input v-model="nickname" maxlength="32" placeholder="你的昵称" /></label><p v-if="profileError" class="cy-message">{{ profileError }}</p></section></main></f7-page></f7-popup></f7-page></template>
<script setup lang="ts">
import {ref} from 'vue';
import LedgerNavigation from '@/components/mobile/LedgerNavigation.vue';
import {useUserStore} from '@/stores/user.ts';
import {useRootStore} from '@/stores/index.ts';
import services from '@/lib/services.ts';
import moment from 'moment-timezone';
import {useLedgerScopeStore} from '@/stores/ledgerScope.ts';
import {investmentError} from '@/lib/investments.ts';
const scope=useLedgerScopeStore();
const user=useUserStore(),root=useRootStore(),recordedDays=ref<number>(),error=ref(''),profileOpen=ref(false),nickname=ref(''),busy=ref(false),profileError=ref('');
async function load(){error.value='';try{const response=await services.getAllTransactions({startTime:0,endTime:moment().add(100,'year').unix(),bookIds:[]});recordedDays.value=new Set(response.data.result.filter(item=>item.type!==1).map(item=>moment.unix(item.time).tz(scope.timeZone).format('YYYY-MM-DD'))).size;}catch(e){error.value=investmentError(e);}}
function openProfile(){nickname.value=user.currentUserNickname||'';profileError.value='';profileOpen.value=true;}
async function saveProfile(){if(busy.value)return;if(!nickname.value.trim()){profileError.value='请填写昵称';return;}busy.value=true;try{await root.updateUserProfile({nickname:nickname.value.trim()});profileOpen.value=false;}catch(e){profileError.value=investmentError(e);}finally{busy.value=false;}}
async function avatar(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;busy.value=true;try{await user.updateUserAvatar({avatarFile:file});}catch(e){profileError.value=investmentError(e);}finally{busy.value=false;}}
</script>
<style scoped>.cy-mine-body{padding-top:20px!important}.cy-mine-more{padding-block:0!important}.cy-mine-profile{display:flex;align-items:center;gap:20px;width:100%;padding:21px 12px 28px;background:none;border:0;color:var(--cy-ink);text-align:left}.cy-mine-profile img,.cy-mine-avatar{width:63px;height:63px;object-fit:cover;border-radius:50%;display:grid;place-items:center;background:var(--cy-soft);color:var(--cy-accent)}.cy-mine-avatar .icon{font-size:31px}.cy-mine-profile h1{font-size:21px;font-weight:600;margin:0}.cy-mine-profile p{font-size:11px;color:var(--cy-muted);margin:12px 0 0}.cy-mine-profile p span{margin-left:7px}.cy-mine-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:30px 5px;padding:27px 9px!important}.cy-mine-grid a{display:flex;flex-direction:column;align-items:center;gap:13px;color:var(--cy-ink);font-size:11px;white-space:nowrap}.cy-mine-grid .icon{font-size:26px;font-weight:400}.cy-mine-links{padding:15px 18px 7px!important}.cy-mine-links h2{font-size:11px;color:var(--cy-muted);font-weight:400;margin:0 0 5px}.cy-mine-links a{display:flex;align-items:center;gap:17px;padding:18px 0;color:var(--cy-ink)}.cy-mine-links a>.icon:first-child{font-size:24px}.cy-mine-links span{flex:1;font-size:14px}.cy-mine-links a>.icon:last-child{font-size:12px;opacity:.35}.cy-profile-form label{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:18px 0;border-bottom:1px solid var(--cy-line)}.cy-profile-form input{border:0;background:transparent;color:var(--cy-ink);max-width:70%;text-align:right}</style>
