<template>
 <f7-page class="cy-main-page cy-mobile-surface cy-statistics" @page:afterin="refresh">
  <template #fixed><LedgerNavigation active="statistics" /></template>
  <header class="stat-top">
   <nav aria-label="统计周期"><button v-for="tab in periods" :key="tab.id" :aria-pressed="period === tab.id" @click="period = tab.id">{{ tab.name }}</button><button class="stat-more" aria-label="统计更多操作" @click="sheet = 'menu'">⋮</button></nav>
   <div v-if="period === 'month'" class="stat-date-strip"><button aria-label="选择年月" @click="monthDialogOpen = true">{{ month.slice(0,4) }}</button><button v-for="item in monthChoices" :key="item.value" :aria-pressed="month === item.value" @click="month = item.value">{{ item.label }}</button></div>
   <div v-else-if="period === 'year'" class="stat-date-strip"><button :aria-pressed="year === 'all'" @click="year = 'all'">所有</button><button v-for="item in yearChoices" :key="item.value" :aria-pressed="year === item.value" @click="year = item.value">{{ item.label }}</button><button @click="sheet = 'date'">选择年份⌄</button></div>
   <div v-else-if="period === 'custom'" class="stat-custom"><button @click="sheet = 'date'">{{ start }} — {{ end }} <span>日期设置⌄</span></button></div>
   <button v-if="filterActive" class="stat-scope" @click="sheet = 'filters'">{{ books.scopeName }} · 已筛选 ⌄</button>
  </header>
  <main class="cy-page-body">
   <p v-if="error || auxiliaryError || rangeError" class="cy-message" role="alert">{{ rangeError || error || auxiliaryError }} <button @click="refresh">重试</button></p>
   <p v-if="loading" class="cy-empty" role="status">正在加载统计…</p>
   <template v-else-if="!rangeError && !error">
    <section v-if="period !== 'daily'" class="cy-panel stat-summary">
     <div class="stat-three"><f7-link v-for="key in metricKeys" :key="key" :href="detail({metric:key,type:key === 'balance' ? '' : key === 'expense' ? '3' : '2',title:metricLabels[key]+'明细'})"><span>{{ periodLabel }}{{ metricLabels[key] }}</span><strong>{{ money(totals[key],totals.complete) }}</strong></f7-link></div>
     <template v-if="summaryExpanded"><div class="stat-summary-grid"><div v-for="key in metricKeys" :key="key"><span>日均{{ metricLabels[key] }}</span><strong>{{ money(new LedgerDecimal(totals[key]).div(dayCount).toString(),totals.complete) }}</strong></div></div><div class="stat-summary-grid"><f7-link v-for="item in auxiliaryRows" :key="item.label" :href="item.href"><span>{{ item.label }}</span><strong>{{ money(item.value,item.complete) }}</strong></f7-link></div></template>
     <button class="stat-expand" :aria-expanded="summaryExpanded" aria-label="展开收支明细汇总" @click="summaryExpanded = !summaryExpanded">{{ summaryExpanded ? '⌃' : '⌄' }}</button>
    </section>
    <p v-if="!totals.complete" class="cy-message">部分外币账单缺少历史汇率，相关汇总显示“—”。点入明细可查看原币金额。</p>
    <template v-for="module in visibleModules" :key="module.id">
     <section v-if="module.id === 'cash'" class="cy-panel">
      <div class="stat-heading"><h2>{{ period === 'daily' ? dailyMode === 'week' ? '本周收支' : '近七日收支' : '收支统计' }} <button class="stat-small" aria-label="放大收支图表" @click="sheet = 'chart'">⛶</button></h2><div class="stat-controls"><button v-if="period === 'daily'" class="stat-small" @click="dailyMode = dailyMode === 'week' ? 'seven' : 'week'">{{ dailyMode === 'week' ? '近七日' : '本周' }} ⇄</button><button class="stat-small" :aria-label="chartKind === 'bar' ? '切换折线图' : '切换柱状图'" @click="chartKind = chartKind === 'bar' ? 'line' : 'bar'">{{ chartKind === 'bar' ? '⌁' : '▥' }}</button><div v-if="period !== 'daily' && period !== 'custom'" class="cy-segments stat-segment"><button v-for="key in metricKeys" :key="key" :aria-pressed="metric === key" @click="metric = key">{{ metricLabels[key] }}</button></div></div></div>
      <StatisticsChart :option="cashOption" :height="period === 'daily' ? 220 : 235" @select="selectBucket" />
      <div v-if="period === 'daily'" class="stat-three stat-daily-summary"><div><span>支出 / 日均</span><strong class="cy-expense">{{ money(totals.expense,totals.complete) }} / {{ money(new LedgerDecimal(totals.expense).div(dayCount).toString(),totals.complete) }}</strong></div><div><span>收入 / 日均</span><strong class="cy-income">{{ money(totals.income,totals.complete) }} / {{ money(new LedgerDecimal(totals.income).div(dayCount).toString(),totals.complete) }}</strong></div></div>
      <f7-link v-if="selectedBucket" class="stat-chart-link" :href="detail({title:selectedBucket.label+'账单'},selectedBucket.from,selectedBucket.to)">{{ selectedBucket.label }} · 查看账单 ›</f7-link>
     </section>
     <section v-else-if="module.id === 'assets'" class="cy-panel"><div class="stat-heading"><h2>资产汇总</h2><f7-link href="/investments">查看详情 ›</f7-link></div><p v-if="wealthError" class="cy-muted">{{ wealthError }}</p><div class="stat-three"><div><span>净资产</span><strong>{{ ledgerMoney(wealth?.netAssets,false) }}</strong></div><div><span>总资产</span><strong>{{ wealth && wealth.netAssets !== null ? ledgerMoney(new LedgerDecimal(wealth.netAssets).plus(wealth.liabilities).toString(),false) : '—' }}</strong></div><div><span>总负债</span><strong>{{ ledgerMoney(wealth?.liabilities,false) }}</strong></div></div><p class="cy-muted stat-footnote">全部账户 · 当前估值</p></section>
     <section v-else-if="module.id === 'budget'" class="cy-panel"><div class="stat-heading"><h2>预算占比</h2><f7-link href="/statistics/budgets">查看详情 ›</f7-link></div><p v-if="!dailyBudgets.length" class="cy-empty">还没有设置预算<br /><f7-link href="/statistics/budgets">设置本月预算 ›</f7-link></p><f7-link v-for="row in dailyBudgets" :key="row.budget.id" class="stat-budget-row" :href="`/statistics/budgets?bookId=${row.budget.bookId}`"><span>{{ bookName(row.budget.bookId) }}<small>剩余 {{ ledgerMoney(row.remaining,false) }} / {{ ledgerMoney(row.available,false) }}</small></span><div class="stat-progress"><i :style="{width:budgetWidth(row)+'%'}" /></div></f7-link></section>
     <section v-else-if="module.id === 'wealth'" class="cy-panel"><WealthTrend :rows="historyRows" v-model:metric="wealthMetric" :from="range[0].unix()" :to="range[1].unix()" :time-zone="scope.timeZone" :error="wealthError" @expand="sheet = 'wealth'" /></section>
     <section v-else-if="module.id === 'heatmap' && year !== 'all'" class="cy-panel"><div class="stat-heading"><h2>收支热力</h2><div class="cy-segments stat-segment"><button v-for="key in ['expense','income'] as const" :key="key" :aria-pressed="heatMetric === key" @click="heatMetric = key">{{ metricLabels[key] }}</button></div></div><div class="stat-heatmaps"><div v-for="grid in heatmaps" :key="grid.month"><h3>{{ grid.month }}月</h3><div class="stat-calendar-grid"><span v-for="i in grid.offset" :key="'blank'+i" /><f7-link v-for="day in grid.days" :key="day.key" :style="{background:day.color}" :aria-label="`${day.key} ${metricLabels[heatMetric]} ${money(day[heatMetric],day.complete)}`" :href="detail({title:day.key},day.from,day.to)">{{ day.day }}</f7-link></div></div></div><p class="cy-muted stat-footnote">颜色越深金额越高，点日期查看账单</p></section>
     <section v-else-if="module.id === 'flow'" class="cy-panel"><div class="stat-heading"><h2>收支对比</h2><div class="cy-segments stat-segment"><button :aria-pressed="flowPrimary" @click="flowPrimary = true">一级分类</button><button :aria-pressed="!flowPrimary" @click="flowPrimary = false">全部</button></div></div><StatisticsChart :option="flowOption" :height="Math.max(210,Math.min(650,flowGroups.length*30))" /><p v-if="flowUnavailable" class="cy-muted">包含净退款或未知金额，请查看分类数据。</p><p v-else-if="!flowGroups.length" class="cy-empty">暂无收支数据</p></section>
     <section v-else-if="['categories','accounts','tagShare'].includes(module.id)" class="cy-panel">
      <div class="stat-heading"><h2>{{ statisticsModuleNames[module.id] }}</h2><div class="cy-segments stat-segment"><button :aria-pressed="shareMetrics[module.id] === 'expense'" @click="shareMetrics[module.id] = 'expense'">支出</button><button :aria-pressed="shareMetrics[module.id] === 'income'" @click="shareMetrics[module.id] = 'income'">收入</button></div></div>
      <div class="stat-pie"><StatisticsChart :option="pieOption(module.id)" :height="255" @select="value => selectGroup(module.id,value.name)" /><button class="stat-pie-center" @click="shareMetrics[module.id] = shareMetrics[module.id] === 'expense' ? 'income' : 'expense'"><span>{{ metricLabels[shareMetrics[module.id]!] }}</span><strong>{{ money(pieBreakdown(module.id).total,pieBreakdown(module.id).complete) }}</strong></button></div>
      <p v-if="!pieBreakdown(module.id).items.length" class="cy-muted stat-center">暂无数据</p><p v-else-if="!pieBreakdown(module.id).canShare" class="cy-muted">包含净退款或未知金额，不绘制占比。</p>
      <div class="stat-options"><select v-if="module.id === 'categories'" v-model="primary" aria-label="分类汇总层级"><option :value="true">一级分类</option><option :value="false">全部分类</option></select><select v-if="module.id === 'tagShare'" v-model="tagMode" aria-label="标签汇总层级"><option v-for="item in tagModes" :key="item.id" :value="item.id">{{ item.label }}</option></select><label><input v-model="showAmounts[module.id]" type="checkbox" />显示金额</label></div>
      <f7-link v-for="item in pieBreakdown(module.id).items" :key="item.id" class="stat-mini-row" :href="groupLink(module.id,item)"><span>{{ item.name }}</span><strong>{{ money(item.amount,item.complete) }} <small v-if="item.percent !== null">{{ item.percent }}%</small> ›</strong></f7-link>
     </section>
     <section v-else-if="module.id === 'ranking'" class="cy-panel"><div class="stat-heading"><h2>分类数据</h2><div class="cy-segments stat-segment"><button :aria-pressed="rankMetric === 'expense'" @click="rankMetric = 'expense'">支出</button><button :aria-pressed="rankMetric === 'income'" @click="rankMetric = 'income'">收入</button></div></div><div class="stat-options"><select v-model="primary" aria-label="排名分类层级"><option :value="true">一级分类</option><option :value="false">全部分类</option></select><label><input v-model="rankDetailed" type="checkbox" />详细模式</label></div><p v-if="!ranking.items.length" class="cy-empty">暂无分类数据</p><f7-link v-for="(item,index) in ranking.items" :key="item.id" class="stat-rank" :href="detail({categoryId:item.id,primary:String(primary),type:rankMetric === 'expense' ? '3' : '2',title:item.name})"><div><i :style="{background:chartColors[index % chartColors.length]}" /><span>{{ item.name }}<small>{{ item.count }} 笔 <template v-if="item.percent !== null">· {{ item.percent }}%</template></small></span><strong>{{ money(item.amount,item.complete) }}</strong></div><div class="stat-progress"><i :style="{width:item.width+'%',background:chartColors[index % chartColors.length]}" /></div><div v-if="rankDetailed" class="stat-comparison"><small>{{ period === 'year' ? '去年同期' : '上月同期' }} {{ comparisonText(item.id,true) }}</small><small>{{ period === 'year' ? '同比去年' : '环比上月' }} {{ comparisonText(item.id,false) }}</small></div></f7-link></section>
     <section v-else-if="module.id === 'report'" class="cy-panel"><div class="stat-heading"><h2>报表统计</h2><select v-model="reportUnit" aria-label="报表时间粒度"><option value="day">按日</option><option value="month">按月</option></select></div><div class="stat-report stat-report-head"><button v-for="column in reportColumns" :key="column.id" @click="sortReport(column.id)">{{ column.label }} {{ reportSort === column.id ? reportDescending ? '↓' : '↑' : '↕' }}</button></div><f7-link v-for="row in shownReport" :key="row.key" class="stat-report" :href="detail({title:row.key+'账单'},row.from,row.to)"><span>{{ row.key }}</span><span class="cy-income">{{ money(row.income,row.complete) }}</span><span class="cy-expense">{{ money(row.expense,row.complete) }}</span><span>{{ money(row.balance,row.complete) }}</span></f7-link><button v-if="reportRows.length > 12" class="stat-expand" @click="allReport = !allReport">{{ allReport ? '收起' : `展开全部 ${reportRows.length} 行` }}</button></section>
     <section v-else-if="module.id === 'tags'" class="cy-panel"><div class="stat-heading"><h2>标签数据</h2><select v-if="period === 'daily'" v-model="dailyTagRange" aria-label="标签统计时段"><option value="month">近一月</option><option value="week">近一周</option><option value="year">今年</option><option value="all">全部</option></select><select v-model="tagSort" aria-label="标签排序"><option value="count">按笔数</option><option value="expense">按支出</option><option value="income">按收入</option><option value="name">按名称</option></select></div><div class="stat-options"><select v-model="tagMode" aria-label="标签数据层级"><option v-for="item in tagModes" :key="item.id" :value="item.id">{{ item.label }}</option></select><f7-link href="/tag/list">管理标签 ›</f7-link></div><p v-if="!tagRows.length" class="cy-empty">暂无标签数据</p><f7-link v-for="item in tagRows" :key="item.id" class="stat-tag-row" :href="detail({tagId:item.id,tagMode,title:item.name},tagRange[0].unix(),tagRange[1].unix())"><span># {{ item.name }}<small>{{ item.count }} 笔</small></span><span><small class="cy-income">收入 {{ money(item.income,item.complete) }}</small><small class="cy-expense">支出 {{ money(item.expense,item.complete) }}</small></span></f7-link></section>
     <section v-else-if="module.id === 'note' && year !== 'all'" class="cy-panel"><div class="stat-heading"><h2>{{ period === 'year' ? '全年' : '本月' }}总结</h2><button class="stat-small" @click="editNote">编辑</button></div><p v-if="books.selectedBookIds.length > 1" class="cy-muted">请选择单个账本，或在全部账本范围填写总结。</p><template v-else><p class="stat-note">{{ currentNote?.content || '记录这段时间的收支变化、消费心得与下期计划。' }}</p><button v-if="currentNote?.content" class="stat-small stat-note-copy" @click="copyNote">复制总结</button></template></section>
    </template>
   </template>
   <p class="cy-muted stat-center">{{ books.scopeName }} · 人民币 · {{ scope.timeZone }}</p>
  </main>
  <StatisticsMonthDialog v-model:open="monthDialogOpen" v-model="month" />
  <StatisticsSheet :open="!!sheet" :title="sheetTitle" :compact="sheet === 'menu'" @update:open="value => { if (!value) sheet = ''; }">
   <template #action><button v-if="sheet === 'modules'" :disabled="saving" @click="saveModules">确定</button><button v-else-if="sheet === 'note'" :disabled="saving" @click="saveNote">保存</button></template>
   <p v-if="actionError" class="cy-message" role="alert">{{ actionError }}</p>
   <template v-if="sheet === 'menu'"><button class="stat-menu-item" @click="sheet = 'filters'">多选账本与筛选 <span>›</span></button><button class="stat-menu-item" @click="openModules">模块设置 <span>›</span></button><button class="stat-menu-item" @click="sheet = 'analysis'">消费分析 <span>›</span></button><f7-link href="/statistics/budgets" class="stat-menu-item" @click="sheet = ''">预算管理 <span>›</span></f7-link></template>
   <template v-else-if="sheet === 'filters'"><BookScope /><LedgerFilters /><button class="cy-button cy-primary" @click="sheet = ''; refresh()">应用筛选</button></template>
   <template v-else-if="sheet === 'date'"><div class="stat-date-form"><label v-if="period === 'month'">选择月份<input v-model="month" type="month" /></label><label v-else-if="period === 'year'">选择年份<input v-model="year" type="number" min="1970" max="2200" /></label><template v-else><label>起始日期<input v-model="start" type="date" /></label><label>结束日期<input v-model="end" type="date" /></label><div class="cy-actions"><button v-for="shortcut in ['本周','本月','上月','今年','去年']" :key="shortcut" class="cy-button" @click="setRange(shortcut)">{{ shortcut }}</button></div></template><button class="cy-button cy-primary" @click="sheet = ''">确定</button></div></template>
   <template v-else-if="sheet === 'modules'"><p class="cy-muted">{{ periods.find(p => p.id === period)?.name }}的模块设置 · 拖动或点箭头调整顺序</p><draggable v-model="moduleDraft" item-key="id" handle=".stat-drag-handle" :delay="180" :delay-on-touch-only="true"><template #item="{element:item,index}"><div class="stat-module-row"><span class="stat-drag-handle" aria-label="长按拖动模块">☰</span><label><input v-model="item.visible" type="checkbox" />{{ statisticsModuleNames[item.id] }}</label><button :disabled="index === 0" :aria-label="'上移'+statisticsModuleNames[item.id]" @click="moveModule(index,index-1)">↑</button><button :disabled="index === moduleDraft.length-1" :aria-label="'下移'+statisticsModuleNames[item.id]" @click="moveModule(index,index+1)">↓</button></div></template></draggable></template>
   <template v-else-if="sheet === 'chart'"><div class="cy-segments"><button v-for="key in metricKeys" :key="key" :aria-pressed="metric === key" @click="metric = key">{{ metricLabels[key] }}</button><button @click="chartKind = chartKind === 'bar' ? 'line' : 'bar'">柱 / 线</button></div><StatisticsChart :option="cashOption" :height="380" @select="selectBucket" /><f7-link v-if="selectedBucket" :href="detail({title:selectedBucket.key},selectedBucket.from,selectedBucket.to)" @click="sheet = ''">{{ selectedBucket.key }} 查看账单 ›</f7-link></template>
   <WealthTrend v-else-if="sheet === 'wealth'" :rows="historyRows" v-model:metric="wealthMetric" :from="range[0].unix()" :to="range[1].unix()" :time-zone="scope.timeZone" :error="wealthError" expanded />
   <template v-else-if="sheet === 'note'"><p class="cy-muted">{{ books.scopeName }} · {{ notePeriod }}</p><textarea v-model="noteDraft" class="stat-textarea" maxlength="10000" rows="14" placeholder="写下本期总结…" /></template>
   <template v-else-if="sheet === 'analysis'"><p class="cy-muted">{{ range[0].format('YYYY-MM-DD') }} 至 {{ range[1].format('YYYY-MM-DD') }} · {{ books.scopeName }}</p><pre class="stat-analysis">{{ analysisText }}</pre><div class="cy-actions"><button class="cy-button" @click="copyText(analysisText)">复制分析</button><button class="cy-button cy-primary" @click="exportAnalysis">导出文本</button></div></template>
   <p v-if="feedback" class="cy-message" role="status">{{ feedback }}</p>
  </StatisticsSheet>
 </f7-page>
</template>
<script setup lang="ts">
import { ref } from 'vue';
import { f7 } from 'framework7-vue';
import draggable from 'vuedraggable';
import BookScope from '@/components/mobile/BookScope.vue';
import LedgerFilters from '@/components/mobile/LedgerFilters.vue';
import StatisticsChart from '@/components/mobile/StatisticsChart.vue';
import StatisticsSheet from '@/components/mobile/StatisticsSheet.vue';
import StatisticsMonthDialog from '@/components/mobile/StatisticsMonthDialog.vue';
import WealthTrend from '@/components/mobile/WealthTrend.vue';
import LedgerNavigation from '@/components/mobile/LedgerNavigation.vue';
import { useStatisticsOverview } from '@/lib/use-statistics-overview.ts';
const monthDialogOpen = ref(false);
const {books,scope,loading,error,period,month,year,start,end,dailyMode,dailyTagRange,periods,metricKeys,metric,chartKind,primary,flowPrimary,summaryExpanded,rankDetailed,rankMetric,shareMetrics,showAmounts,tagMode,tagSort,heatMetric,tagModes,sheet,saving,actionError,feedback,auxiliaryError,sheetTitle,moduleDraft,noteDraft,visibleModules,monthChoices,yearChoices,range,rangeError,totals,dayCount,periodLabel,filterActive,selectedBucket,cashOption,selectBucket,money,detail,bookName,flowGroups,flowOption,flowUnavailable,pieGroups,pieBreakdown,pieOption,groupLink,ranking,comparisonText,reportUnit,reportSort,reportDescending,allReport,reportColumns,reportRows,shownReport,sortReport,tagRange,tagRows,heatmaps,wealth,wealthError,wealthMetric,historyRows,dailyBudgets,budgetWidth,auxiliaryRows,notePeriod,currentNote,editNote,saveNote,openModules,moveModule,saveModules,setRange,analysisText,copyText,copyNote,exportAnalysis,refresh,statisticsModuleNames,chartColors,metricLabels,ledgerMoney,LedgerDecimal}=useStatisticsOverview();
function selectGroup(id:string,name:string){const group=pieGroups(id).find(item=>item.name===name);if(group)f7.views.main.router.navigate(groupLink(id,group));}
</script>
<style scoped src="@/styles/mobile/statistics.css"></style>
