<template><f7-page class="cy-mobile-surface" @page:afterin="load"><f7-navbar title="愿望清单" back-link="返回"><f7-nav-right><f7-link @click="add">添加</f7-link></f7-nav-right></f7-navbar><main class="cy-page-body">
    <div class="cy-segment"><button :aria-pressed="!archived" @click="archived=false">进行中</button><button :aria-pressed="archived" @click="archived=true">已归档</button></div><p v-if="error || ledger.error.value" class="cy-message">{{ error || ledger.error.value }} <button @click="load">重试</button></p><p v-if="loading" class="cy-helper">正在读取愿望…</p><p v-else-if="!visible.length" class="cy-empty">{{ archived?'暂无归档愿望':'把想实现的事记在这里' }}</p>
    <section v-for="wish in visible" :key="wish.id" class="cy-panel cy-wish"><button class="cy-wish-heading" @click="edit(wish)"><f7-icon :f7="wish.data.icon" /><span>{{ wish.data.name }}<small>{{ wish.data.note || modes[wish.data.mode] }}</small></span><f7-icon f7="chevron_right" size="14" /></button><div class="cy-wish-amount"><strong>{{ money(progress(wish).saved) }}</strong><span>/ {{ money(wish.data.target) }}</span><b>{{ progress(wish).percent.toFixed(1) }}%</b></div><div class="cy-wish-track"><i :style="{width:`${progress(wish).percent}%`}" /></div><p>{{ progress(wish).achieved?'愿望已达成':`还差 ${money(progress(wish).remaining)}` }}<span v-if="progress(wish).daysRemaining!==null">{{ progress(wish).daysRemaining!>=0?`剩余 ${progress(wish).daysRemaining} 天`:'已到目标日期' }}</span></p><div class="cy-wish-actions"><button class="cy-button" @click="openLogs(wish)">储蓄记录</button><button v-if="!wish.data.archived" class="cy-button cy-accent-button" @click="openLog(wish)">存入 / 取出</button><button v-else class="cy-button" :disabled="busy" @click="archive(wish,false)">恢复愿望</button></div></section>
</main><f7-popup v-model:opened="editor" class="cy-mobile-surface"><f7-page><f7-navbar :title="draft?.id?'编辑愿望':'新建愿望'"><f7-nav-left><f7-link popup-close>取消</f7-link></f7-nav-left><f7-nav-right><f7-link :class="{disabled:busy}" @click="save">保存</f7-link></f7-nav-right></f7-navbar><main v-if="draft" class="cy-page-body cy-wish-form"><p v-if="editError" class="cy-message">{{ editError }}</p><section class="cy-panel"><label>愿望名称<input v-model="draft.data.name" maxlength="64" placeholder="给愿望起个名字" /></label><div class="cy-wish-icons"><button v-for="icon in icons" :key="icon" :aria-pressed="draft.data.icon===icon" @click="draft.data.icon=icon"><f7-icon :f7="icon" /></button></div><label>目标金额<input v-model="draft.data.target" inputmode="decimal" maxlength="18" placeholder="0.00" /></label><label>初始储蓄<input v-model="draft.data.initial" inputmode="decimal" maxlength="18" /></label><label>开始日期<input v-model="draft.data.startDate" type="date" /></label><label>目标日期<input v-model="draft.data.endDate" type="date" /></label><label>储蓄方式<select v-model="draft.data.mode"><option v-for="(name,value) in modes" :key="value" :value="value">{{ name }}</option></select></label>
    <template v-if="draft.data.mode==='schedule'"><label>储蓄周期<select v-model="draft.data.cycle"><option value="day">每天</option><option value="week">每周</option><option value="month">每月</option><option value="year">每年</option></select></label><label>每期金额<input v-model="draft.data.amount" inputmode="decimal" maxlength="18" /></label></template><label v-if="['income','balance','asset'].includes(draft.data.mode)">计入比例(%)<input v-model="draft.data.ratio" inputmode="decimal" maxlength="6" /></label>
    <LedgerScopeFields v-if="['income','balance','asset'].includes(draft.data.mode)" v-model:book-ids="draft.data.bookIds" v-model:account-ids="draft.data.accountIds" v-model:category-ids="draft.data.incomeCategoryIds" :accounts-enabled="draft.data.mode==='asset'" :categories-enabled="draft.data.mode==='income'" />
    <details v-if="draft.data.mode==='balance'"><summary>收入与支出分类</summary><label v-for="category in Object.values(categories.allTransactionCategoriesMap).filter(c=>c.parentId!=='0')" :key="category.id"><span>{{ category.name }}</span><input v-if="category.type===1" v-model="draft.data.incomeCategoryIds" type="checkbox" :value="category.id" /><input v-else-if="category.type===2" v-model="draft.data.expenseCategoryIds" type="checkbox" :value="category.id" /></label></details>
    <label>备注<textarea v-model="draft.data.note" rows="3" maxlength="1000" placeholder="写下你的计划" /></label><p class="cy-helper">愿望用来记录储蓄计划，不会自动转账或改变账户余额。自动进度按现有账单、账户余额或设定的周期计算。</p>
</section><div v-if="draft.id" class="cy-wish-actions"><button class="cy-button" :disabled="busy" @click="archive(draft,!draft.data.archived)">{{ draft.data.archived?'恢复愿望':'归档愿望' }}</button><button class="cy-button cy-danger" :disabled="busy" @click="remove">删除愿望</button></div></main></f7-page></f7-popup>
<f7-popup v-model:opened="logsOpen" class="cy-mobile-surface"><f7-page><f7-navbar :title="activeWish?.data.name || '储蓄记录'"><f7-nav-right><f7-link popup-close>关闭</f7-link></f7-nav-right></f7-navbar><main class="cy-page-body"><section v-if="logging" class="cy-panel cy-wish-form"><div class="cy-segment"><button :aria-pressed="!withdrawing" @click="withdrawing=false">存入</button><button :aria-pressed="withdrawing" @click="withdrawing=true">取出</button></div><label>金额<input v-model="logAmount" inputmode="decimal" maxlength="18" /></label><label>日期<input v-model="logDate" type="date" /></label><label>备注<input v-model="logNote" maxlength="255" /></label><p v-if="editError" class="cy-message">{{ editError }}</p><button class="cy-button cy-primary-action" :disabled="busy" @click="saveLog">保存记录</button></section><section v-for="log in activeWish?.data.logs.slice().reverse()" :key="log.id" class="cy-panel cy-log-row"><span>{{ log.date }}<small>{{ log.note || '储蓄记录' }}</small></span><strong :class="log.amount.startsWith('-')?'cy-expense':'cy-income'">{{ money(log.amount) }}</strong><button class="cy-button" :disabled="busy" @click="deleteLog(log.id)">删除</button></section><p v-if="!activeWish?.data.logs.length" class="cy-empty">暂无手动储蓄记录</p></main></f7-page></f7-popup></f7-page></template>
<script setup lang="ts">
import {computed,ref} from 'vue';
import moment from 'moment-timezone';
import {ledgerWorkspace,newLedgerWish,wishProgress,type LedgerWish,type LedgerWorkspaceItem} from '@/lib/ledger-workspace.ts';
import {useMobileLedger,LedgerDecimal,ledgerMoney} from '@/lib/mobile-ledger.ts';
import {useAccountsStore} from '@/stores/account.ts';
import {useTransactionCategoriesStore} from '@/stores/transactionCategory.ts';
import {useLedgerScopeStore} from '@/stores/ledgerScope.ts';
import LedgerScopeFields from '@/components/mobile/LedgerScopeFields.vue';
import {investmentError} from '@/lib/investments.ts';
import {useI18nUIComponents} from '@/lib/ui/mobile.ts';
const scope=useLedgerScopeStore(),accounts=useAccountsStore(),categories=useTransactionCategoriesStore(),ledger=useMobileLedger({bookIds:()=>[],applyFilters:()=>false}),{showConfirm}=useI18nUIComponents();
const items=ref<LedgerWorkspaceItem<LedgerWish>[]>([]),draft=ref<LedgerWorkspaceItem<LedgerWish>>(),activeWish=ref<LedgerWorkspaceItem<LedgerWish>>(),error=ref(''),editError=ref(''),loading=ref(false),busy=ref(false),editor=ref(false),archived=ref(false),logsOpen=ref(false),logging=ref(false),withdrawing=ref(false),logAmount=ref(''),logDate=ref(''),logNote=ref('');
const modes={manual:'手动储蓄',schedule:'周期计划',income:'收入比例',balance:'结余比例',asset:'关联账户余额'},icons=['star','gift','airplane','house','car','camera','device_laptop','heart','book','bag','leaf_arrow_circlepath','flag'];
const visible=computed(()=>items.value.filter(w=>w.data.archived===archived.value));
function money(value:string|null){return value===null?'待换算':ledgerMoney(value,false);}
function progress(wish:LedgerWorkspaceItem<LedgerWish>){return wishProgress(wish.data,ledger.entries.value,accounts.allAccountsMap,moment().tz(scope.timeZone));}
async function load(){loading.value=true;error.value='';try{await ledger.load(0,moment().add(100,'year').unix());items.value=await ledgerWorkspace.wishes();}catch(e){error.value=investmentError(e);}finally{loading.value=false;}}
function add(){draft.value=newLedgerWish(scope.timeZone);editError.value='';editor.value=true;}
function edit(wish:LedgerWorkspaceItem<LedgerWish>){draft.value=copy(wish);editError.value='';editor.value=true;}
function copy(wish:LedgerWorkspaceItem<LedgerWish>):LedgerWorkspaceItem<LedgerWish>{return JSON.parse(JSON.stringify(wish));}
async function persist(wish:LedgerWorkspaceItem<LedgerWish>){const saved=await ledgerWorkspace.save(wish);items.value=[saved,...items.value.filter(w=>w.id!==saved.id)];if(activeWish.value?.id===saved.id)activeWish.value=saved;return saved;}
async function save(){if(!draft.value||busy.value)return;busy.value=true;editError.value='';try{await persist(draft.value);editor.value=false;}catch(e){editError.value=investmentError(e);}finally{busy.value=false;}}
async function archive(wish:LedgerWorkspaceItem<LedgerWish>,value:boolean){busy.value=true;try{const next=copy(wish);next.data.archived=value;await persist(next);editor.value=false;}catch(e){error.value=editError.value=investmentError(e);}finally{busy.value=false;}}
function remove(){if(!draft.value)return;const item=copy(draft.value);showConfirm('删除这个愿望和储蓄记录？账户余额不会改变。',async()=>{busy.value=true;try{await ledgerWorkspace.delete(item);items.value=items.value.filter(w=>w.id!==item.id);editor.value=false;}catch(e){editError.value=investmentError(e);}finally{busy.value=false;}});}
function openLogs(wish:LedgerWorkspaceItem<LedgerWish>){activeWish.value=wish;logging.value=false;logsOpen.value=true;}
function openLog(wish:LedgerWorkspaceItem<LedgerWish>){openLogs(wish);logging.value=true;withdrawing.value=false;logAmount.value='';logDate.value=moment().tz(scope.timeZone).format('YYYY-MM-DD');logNote.value='';editError.value='';}
async function saveLog(){if(!activeWish.value||busy.value)return;editError.value='';if(!/^\d{1,12}(\.\d{1,2})?$/.test(logAmount.value)||!new LedgerDecimal(logAmount.value).gt(0)){editError.value='请输入大于零、最多两位小数的金额';return;}busy.value=true;try{const next=copy(activeWish.value);next.data.logs.push({id:crypto.randomUUID(),date:logDate.value,amount:(withdrawing.value?'-':'')+logAmount.value,note:logNote.value});await persist(next);logging.value=false;}catch(e){editError.value=investmentError(e);}finally{busy.value=false;}}
function deleteLog(id:string){if(!activeWish.value)return;showConfirm('删除这条储蓄记录？',async()=>{busy.value=true;try{const next=copy(activeWish.value!);next.data.logs=next.data.logs.filter(log=>log.id!==id);await persist(next);}catch(e){editError.value=error.value=investmentError(e);}finally{busy.value=false;}});}
</script>
<style scoped>.cy-helper{font-size:12px;line-height:1.7;color:var(--cy-muted)}.cy-segment{display:flex;justify-content:center;gap:8px;margin:8px 0 18px}.cy-segment button{border:0;border-radius:18px;background:transparent;padding:8px 22px;color:var(--cy-muted)}.cy-segment button[aria-pressed=true]{background:var(--cy-soft);color:var(--cy-accent)}.cy-wish-heading{display:flex;align-items:center;width:100%;gap:14px;padding:0;border:0;background:none;text-align:left;color:var(--cy-ink)}.cy-wish-heading>.icon:first-child{background:var(--cy-soft);color:var(--cy-accent);padding:12px;border-radius:12px;font-size:26px}.cy-wish-heading span{flex:1;font-size:17px}.cy-wish-heading small{display:block;font-size:11px;color:var(--cy-muted);margin-top:6px}.cy-wish-amount{display:flex;align-items:baseline;gap:6px;margin-top:22px}.cy-wish-amount strong{font-size:27px}.cy-wish-amount span{font-size:12px;color:var(--cy-muted)}.cy-wish-amount b{margin-left:auto;font-size:12px;color:var(--cy-accent)}.cy-wish-track{height:6px;border-radius:3px;background:var(--cy-soft);margin:12px 0}.cy-wish-track i{display:block;height:100%;background:var(--cy-accent);border-radius:3px}.cy-wish>p{display:flex;justify-content:space-between;font-size:11px;color:var(--cy-muted)}.cy-wish-actions{display:flex;justify-content:space-between;gap:10px;margin-top:20px}.cy-accent-button{color:var(--cy-accent)!important}.cy-wish-form label{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 0;border-bottom:1px solid var(--cy-line);font-size:14px}.cy-wish-form input:not([type=checkbox]),.cy-wish-form select,.cy-wish-form textarea{max-width:62%;min-width:0;text-align:right;background:transparent;color:var(--cy-ink);border:0;padding:4px}.cy-wish-icons{display:flex;flex-wrap:wrap;gap:8px;padding:14px 0}.cy-wish-icons button{width:42px;height:42px;border:0;border-radius:10px;color:var(--cy-muted);background:var(--cy-bg)}.cy-wish-icons button[aria-pressed=true]{background:var(--cy-soft);color:var(--cy-accent)}.cy-log-row{display:flex;align-items:center;gap:10px}.cy-log-row span{flex:1;font-size:14px}.cy-log-row small{display:block;color:var(--cy-muted);margin-top:6px;font-size:12px}.cy-danger{color:var(--cy-expense)}</style>
