<template><f7-page class="cy-mobile-surface" @page:afterin="load"><f7-navbar title="数据备份" back-link="返回"/><main class="cy-backup-body"><p class="cy-muted">完整备份包括账本、资产、投资、附件与界面设置。备份保存在这部手机中，也可导出到自己选择的位置。</p><p v-if="!native" class="cy-message">手机完整备份请在 CYLedger 应用内使用；电脑部署可运行项目的 backup.py 备份命令。</p><p v-if="message" class="cy-message" role="status">{{message}}</p><div class="cy-backup-actions"><button class="cy-button cy-button-primary" :disabled="!native||busy" @click="backup">立即备份</button><button class="cy-button" :disabled="!native||busy" @click="restore">从文件恢复</button></div><f7-list strong inset><f7-list-item title="每天打开时自动备份" footer="仅保存在手机内，卸载应用会删除这些备份"><template #after><f7-toggle :checked="automatic" :disabled="!native" @toggle:change="auto"/></template></f7-list-item></f7-list><f7-block-title>本机备份 · {{items.length}} 份</f7-block-title><article v-for="item in items" :key="item.name" class="cy-panel"><strong>{{moment(item.time).format('YYYY-MM-DD HH:mm:ss')}}</strong><p>{{size(item.size)}} · 完整备份</p><small>{{item.name}}</small><div class="cy-backup-actions"><button class="cy-button" @click="exportFile(item.name)">导出文件</button><button class="cy-button" @click="remove(item.name)">删除</button></div></article><p v-if="native&&!items.length" class="cy-muted">还没有备份，先创建一份。</p></main></f7-page></template>
<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue';import moment from 'moment-timezone';import {isNativePersonalMode,localBackupSettings,syncNativeSettings} from '@/lib/native.ts';
interface Backup{name:string;size:string;time:number}const native=isNativePersonalMode(),items=ref<Backup[]>([]),automatic=ref(false),message=ref(''),busy=ref(false);
function load(){try{items.value=JSON.parse(window.CYLedgerLocal?.backups()||'[]');automatic.value=JSON.parse(window.CYLedgerLocal?.status()||'{}').autoBackup===true;}catch{message.value='无法读取备份列表';}}
function size(value:string){return `${(Number(value)/1024/1024).toFixed(2)} MB`;}
function change(event:Event){const text=(event as CustomEvent<string>).detail;if(text)message.value=text;busy.value=text==='正在创建完整备份…'||text==='正在校验备份…';load();}
function backup(){busy.value=true;message.value='正在创建完整备份…';window.CYLedgerLocal?.backup(localBackupSettings());}
function restore(){syncNativeSettings();window.CYLedgerLocal?.restore();}function exportFile(name:string){window.CYLedgerLocal?.exportBackup(name);}function remove(name:string){window.CYLedgerLocal?.deleteBackup(name);}function auto(enabled:boolean){syncNativeSettings();window.CYLedgerLocal?.action('autoBackup',JSON.stringify({enabled}));}
onMounted(()=>window.addEventListener('cyledger-native-change',change));onUnmounted(()=>window.removeEventListener('cyledger-native-change',change));
</script><style scoped>.cy-backup-body{padding:12px 16px 70px}.cy-backup-body small{display:block;overflow-wrap:anywhere;color:var(--cy-muted)}.cy-backup-actions{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}.cy-backup-body article p{font-size:13px;color:var(--cy-muted)}</style>
