<template><f7-page class="cy-mobile-surface" @page:afterin="load"><f7-navbar title="导入导出" back-link="返回"/><main class="cy-data-body"><p v-if="error" class="cy-message">{{error}}</p><p v-if="busy" role="status">{{progress||'正在处理…'}}</p><f7-list strong inset><f7-list-item title="导入账单文件 / 截图" link="/user/import"/><f7-list-item title="下载导入模板" link="#" @click="template"/></f7-list><f7-block-title>导出数据</f7-block-title><p class="cy-muted">CSV / Excel 用于查看和交换账单。完整还原附件、优惠、手续费关联及所有设置，请使用数据备份。</p><div class="cy-panel"><div class="cy-data-dates"><label>开始日期<input type="date" v-model="start"/></label><label>结束日期<input type="date" v-model="end"/></label></div><ledger-scope-fields accounts-enabled categories-enabled tags-enabled v-model:book-ids="bookIds" v-model:account-ids="accountIds" v-model:category-ids="categoryIds" v-model:tag-ids="tagIds"/><label class="cy-data-type">账单类型<select v-model="type"><option value="all">全部</option><option value="expense">支出</option><option value="income">收入</option><option value="transfer">转账</option><option value="debt">债务往来</option></select></label><p>所选范围 {{filtered.length}} 笔</p><button class="cy-button" :disabled="busy" @click="exportCsv">导出 CSV</button><button class="cy-button" :disabled="busy" @click="exportXlsx">导出 Excel</button><button class="cy-button" :disabled="busy" @click="pictures">导出账单图片</button></div><f7-list strong inset><f7-list-item title="导出资产账户 Excel" link="#" @click="assets"/><f7-list-item title="导出投资与加密资产流水" link="#" @click="investment"/></f7-list><f7-block-title>导入记录</f7-block-title><div v-for="batch in batches" :key="batch.id" class="cy-panel cy-import-batch"><div><strong>{{batch.name||'账单导入'}}</strong><p>{{moment.unix(batch.createdAt).tz(scope.timeZone).format('YYYY-MM-DD HH:mm')}} · {{batch.count}} 笔</p></div><button class="cy-button" :disabled="busy||batch.deleted" @click="undo(batch)">{{batch.deleted?'已撤回':'撤回'}}</button></div><p v-if="!batches.length" class="cy-muted">暂无导入记录</p></main></f7-page></template>
<script setup lang="ts">
import {ref,computed} from 'vue';import {f7} from 'framework7-vue';import axios from 'axios';import moment from 'moment-timezone';
import LedgerScopeFields from '@/components/mobile/LedgerScopeFields.vue';import {useMobileLedger,LedgerDecimal} from '@/lib/mobile-ledger.ts';import {useLedgerScopeStore} from '@/stores/ledgerScope.ts';import {useAccountsStore} from '@/stores/account.ts';import {ledgerEntryRows,exportLedgerEntries,exportLedgerWorkbook,exportLedgerPictures,downloadLedgerFile} from '@/lib/ledger-export.ts';import {investments,investmentError} from '@/lib/investments.ts';
const ledger=useMobileLedger({bookIds:()=>[],applyFilters:()=>false}),scope=useLedgerScopeStore(),accounts=useAccountsStore(),start=ref(''),end=ref(''),bookIds=ref<string[]>([]),accountIds=ref<string[]>([]),categoryIds=ref<string[]>([]),tagIds=ref<string[]>([]),type=ref('all'),error=ref(''),busy=ref(false),progress=ref('');
interface Batch{id:string;name:string;count:string;createdAt:number;deleted:boolean}const batches=ref<Batch[]>([]);
const filtered=computed(()=>ledger.entries.value.filter(e=>(!start.value||e.day>=start.value)&&(!end.value||e.day<=end.value)&&(!bookIds.value.length||bookIds.value.includes(e.bookId))&&(!accountIds.value.length||accountIds.value.includes(e.accountId)||accountIds.value.includes(e.destinationAccountId))&&(!categoryIds.value.length||categoryIds.value.includes(e.categoryId)||categoryIds.value.includes(e.primaryCategoryId))&&(!tagIds.value.length||tagIds.value.some(t=>e.tagIds.includes(t)))&&(type.value==='all'||e.type===({expense:3,income:2,transfer:4} as Record<string,number>)[type.value]||type.value==='debt'&&[e.accountId,e.destinationAccountId].some(id=>[5,6].includes(accounts.allAccountsMap[id]?.category||0)))));
async function load(){await ledger.load(0,moment().add(100,'year').unix());try{batches.value=(await axios.get('v1/ledger/imports')).data.result;}catch(e){error.value=investmentError(e);}}
function exportCsv(){exportLedgerEntries(filtered.value,scope.timeZone);}function exportXlsx(){exportLedgerWorkbook(ledgerEntryRows(filtered.value,scope.timeZone));}
async function run(action:()=>Promise<void>){busy.value=true;error.value='';try{await action();}catch(e){error.value=investmentError(e);}finally{busy.value=false;progress.value='';}}
function pictures(){return run(()=>exportLedgerPictures(filtered.value,scope.timeZone,value=>progress.value=value));}
function investment(){return run(async()=>downloadLedgerFile(await investments.export(),`OpenBill-投资-${moment().format('YYYYMMDD-HHmmss')}.csv`,'text/csv;charset=utf-8'));}
function assets(){exportLedgerWorkbook([['账户','币种','余额','类型','计入总资产'],...accounts.allPlainAccounts.filter(a=>!a.subAccounts?.length).map(a=>[a.name,a.currency,new LedgerDecimal(a.balance).div(100).toFixed(2),a.assetProfile.kind||'',a.assetProfile.excludeFromTotal?'否':'是'])],'资产账户');}
function template(){exportLedgerWorkbook([['日期','类型','分类','子分类','账户','币种','金额','账户2','账户2币种','账户2金额','标签','备注'],['2026-01-01 12:00:00','支出','餐饮','早餐','现金','CNY','12.50','','','','','示例，请替换为自己的数据']],'导入模板');}
function undo(batch:Batch){f7.dialog.confirm(`撤回「${batch.name}」尚存在的全部账单，并恢复对应余额。后续修改过的导入账单也包含在内。`,'撤回导入',()=>run(async()=>{await axios.post('v1/ledger/imports/undo',{id:batch.id});await accounts.loadAllAccounts({force:true});await load();}));}
</script><style scoped>.cy-data-body{padding:12px 14px 80px}.cy-data-dates{display:grid;grid-template-columns:1fr 1fr;gap:12px}.cy-data-dates input,.cy-data-type select{display:block;width:100%;padding:9px 0;color:var(--cy-ink);background:transparent}.cy-data-type{display:block;margin-top:12px}.cy-data-body .cy-button{margin:6px 8px 6px 0}.cy-import-batch{display:flex;gap:12px;justify-content:space-between;align-items:center;overflow-wrap:anywhere}.cy-import-batch p{font-size:12px;color:var(--cy-muted)}</style>
