<template>
<f7-page class="cy-mobile-surface" @page:afterin="load"><f7-navbar title="导入账单" back-link="返回"/><main class="cy-import-body">
<p class="cy-muted">选择文件或微信 / 支付宝账单截图，核对预览后导入。</p><p v-if="error" class="cy-message">{{error}}</p><p v-if="busy" role="status">{{progress||'正在处理…'}}</p>
<f7-list strong inset><f7-list-input label="导入方式" type="select" v-model:value="fileType" :disabled="busy||rows.length>0"><option value="screenshot">微信 / 支付宝截图（离线）</option><option v-for="type in types" :key="type.type" :value="type.type">{{type.name}}</option></f7-list-input><f7-list-input label="存入账本" type="select" v-model:value="bookId"><option v-for="book in books.allBooks.filter(b=>!b.archived)" :key="book.id" :value="book.id">{{book.name}}</option></f7-list-input><f7-list-input v-if="fileType!=='screenshot'" label="文件编码" type="select" v-model:value="encoding"><option value="utf-8">UTF-8</option><option value="gb18030">GB18030 / GBK</option><option value="utf-16le">UTF-16</option></f7-list-input></f7-list>
<input ref="picker" class="cy-import-file" type="file" :accept="accept" :multiple="fileType==='screenshot'" :disabled="busy" @change="choose"/>
<button v-if="!rows.length" class="cy-button cy-button-primary" :disabled="busy" @click="picker?.click()">选择{{fileType==='screenshot'?'截图':'账单文件'}}</button>
<details v-if="table.length" class="cy-panel"><summary>字段对应关系</summary><p class="cy-muted">{{file?.name}} · {{table.length-1}} 行</p><label v-for="field in fields" :key="field.type" class="cy-import-field">{{tt(field.name)}}<select :value="mapping[field.type]??-1" @change="map(field.type,Number(($event.target as HTMLSelectElement).value))"><option value="-1">不导入</option><option v-for="(cell,i) in table[0]" :key="i" :value="i">第 {{i+1}} 列 · {{cell}}</option></select></label><label class="cy-import-field">日期格式<input v-model="dateFormat" placeholder="YYYY-MM-DD HH:mm:ss"/></label></details><button v-if="table.length" class="cy-button" :disabled="busy" @click="parseFile">生成预览</button>
<details v-if="ocrText" class="cy-panel"><summary>查看识别文字</summary><pre class="cy-ocr-text">{{ocrText}}</pre><p>未识别出的账单可在下方手动补一笔；日期缺失时暂填今天，时间缺失时暂填 12:00，请核对。</p></details>
<template v-if="rows.length||ocrText"><div class="cy-panel"><strong>预览 · 已选 {{selected.length}} 笔</strong><p>账户、分类或金额不完整时无法入账。相同时间、金额、账户及备注的账单默认取消勾选。</p><label class="cy-import-field">统一账户<select v-model="bulkAccount"><option value="">请选择</option><option v-for="a in accountChoices" :key="a.id" :value="a.id">{{a.name}} · {{a.currency}}</option></select></label><button class="cy-button" @click="applyAccount">应用至已选</button><label class="cy-import-field">统一分类<select v-model="bulkCategory"><option value="">请选择</option><option v-for="c in categoryChoices" :key="c.id" :value="c.id">{{c.name}}</option></select></label><button class="cy-button" @click="applyCategory">应用至同类型的已选账单</button><button class="cy-button" @click="selectValid">仅选择有效且不重复的账单</button></div>
<details v-for="row in visibleRows" :key="row.index" class="cy-panel cy-import-row" :open="!valid(row)"><summary><input v-model="row.selected" type="checkbox" @click.stop/> {{moment.unix(row.time).tz(scope.timeZone).format('MM-DD')}} · {{row.comment||row.originalCategoryName||'账单'}} <b>{{amount(row.sourceAmount)}}</b><small>{{duplicates.has(row.index)?'疑似重复':valid(row)?'待确认':'请补全'}}</small></summary><label class="cy-import-field">类型<select v-model.number="row.type"><option :value="2">收入</option><option :value="3">支出</option><option :value="4">转账</option></select></label><label class="cy-import-field">日期时间<input type="datetime-local" :value="moment.unix(row.time).tz(scope.timeZone).format('YYYY-MM-DDTHH:mm')" @change="date(row,($event.target as HTMLInputElement).value)"/></label><label class="cy-import-field">金额<input inputmode="decimal" :value="amount(row.sourceAmount)" @change="money(row,'sourceAmount',($event.target as HTMLInputElement).value)"/></label><label class="cy-import-field">币种<input v-model="row.originalSourceAccountCurrency" maxlength="3"/></label><label class="cy-import-field">账户<select v-model="row.sourceAccountId"><option value="">{{row.originalSourceAccountName||'请选择'}}</option><option v-for="a in accountChoices" :key="a.id" :value="a.id">{{a.name}} · {{a.currency}}</option></select></label><label class="cy-import-field">分类<select v-model="row.categoryId"><option value="">{{row.originalCategoryName||'请选择'}}</option><option v-for="c in categoryChoices.filter(c=>c.type===row.type-1)" :key="c.id" :value="c.id">{{c.name}}</option></select></label><template v-if="row.type===4"><label class="cy-import-field">转入账户<select v-model="row.destinationAccountId"><option value="">请选择</option><option v-for="a in accountChoices" :key="a.id" :value="a.id">{{a.name}} · {{a.currency}}</option></select></label><label class="cy-import-field">转入金额<input inputmode="decimal" :value="amount(row.destinationAmount)" @change="money(row,'destinationAmount',($event.target as HTMLInputElement).value)"/></label></template><label class="cy-import-field">备注<textarea v-model="row.comment" maxlength="255"/></label><p v-if="!valid(row)" class="cy-message">请核对时间、金额、账户币种与分类，转账双方不能相同。</p></details>
<button v-if="limit<rows.length" class="cy-button" @click="limit+=100">显示更多预览</button><button class="cy-button" @click="addRow">手动补一笔</button><button class="cy-button cy-button-primary" :disabled="busy||!selected.length||selected.some(r=>!valid(r))" @click="commit">确认导入 {{selected.length}} 笔</button><button class="cy-button" :disabled="busy" @click="reset">重新选择文件</button></template>
<p v-if="finished" class="cy-message">{{finished}}</p></main></f7-page>
</template>
<script setup lang="ts">
import {ref,computed} from 'vue';
import {f7} from 'framework7-vue';
import moment from 'moment-timezone';
import {useI18n} from '@/locales/helpers.ts';
import services from '@/lib/services.ts';
import {investmentError} from '@/lib/investments.ts';
import {SUPPORTED_IMPORT_FILE_CATEGORY_AND_TYPES} from '@/consts/file.ts';
import {KNOWN_COLUMN_NAME_MAPPING} from '@/consts/import_transaction.ts';
import {ImportTransactionColumnType} from '@/core/import_transaction.ts';
import {ImportTransaction} from '@/models/imported_transaction.ts';
import {useMobileLedger,LedgerDecimal} from '@/lib/mobile-ledger.ts';
import {useBooksStore} from '@/stores/books.ts';
import {useLedgerScopeStore} from '@/stores/ledgerScope.ts';
import {useAccountsStore} from '@/stores/account.ts';
import {useTransactionCategoriesStore} from '@/stores/transactionCategory.ts';
import {ledgerWorkspace,keywordMatch,type LedgerWorkspaceItem,type LedgerKeyword} from '@/lib/ledger-workspace.ts';
import {useLedgerExperienceStore} from '@/stores/ledgerExperience.ts';
import {recognizeBillImages} from '@/lib/ledger-ocr.ts';
const experience=useLedgerExperienceStore();
const {tt}=useI18n(),books=useBooksStore(),scope=useLedgerScopeStore(),accounts=useAccountsStore(),categories=useTransactionCategoriesStore(),ledger=useMobileLedger({bookIds:()=>[],applyFilters:()=>false});
const fileType=ref('custom_csv'),encoding=ref('utf-8'),bookId=ref(''),file=ref<File>(),picker=ref<HTMLInputElement>(),table=ref<string[][]>([]),mapping=ref<Record<number,number>>({}),dateFormat=ref('YYYY-MM-DD HH:mm:ss'),rows=ref<ImportTransaction[]>([]),busy=ref(false),error=ref(''),progress=ref(''),ocrText=ref(''),finished=ref(''),limit=ref(100),bulkAccount=ref(''),bulkCategory=ref(''),batchId=ref(crypto.randomUUID()),duplicates=ref(new Set<number>());
let rules:LedgerWorkspaceItem<LedgerKeyword>[]=[];
const types=SUPPORTED_IMPORT_FILE_CATEGORY_AND_TYPES.flatMap(group=>group.fileTypes.filter(type=>!type.needAIImageRecognition&&!type.needAITextRecognition&&type.type!=='custom_js'&&!type.dataFromTextbox).flatMap(type=>type.subTypes?.length?type.subTypes.map(sub=>({type:sub.type,name:`${tt(type.name)} · ${tt(sub.name)}`,extensions:sub.extensions||type.extensions})):({type:type.type,name:tt(type.name),extensions:type.extensions})));
const fields=ImportTransactionColumnType.values(),accept=computed(()=>fileType.value==='screenshot'?'image/*':types.find(t=>t.type===fileType.value)?.extensions||'.csv,.xlsx,.xls');
const accountChoices=computed(()=>accounts.allPlainAccounts.filter(a=>!a.hidden&&!a.subAccounts?.length));
const categoryChoices=computed(()=>Object.values(categories.allTransactionCategoriesMap).filter(c=>!c.hidden&&c.parentId!=='0'&&!!c.parentId));
const selected=computed(()=>rows.value.filter(r=>r.selected)),visibleRows=computed(()=>rows.value.slice(0,limit.value));
async function load(){await ledger.load(0,moment().add(100,'year').unix());rules=await ledgerWorkspace.keywords().catch(()=>[]);bookId.value ||= books.selectedBookIds[0]||books.defaultBookId||books.allBooks[0]?.id||'';}
function amount(cents:number){return Number.isSafeInteger(cents)?new LedgerDecimal(cents).div(100).toFixed(2):'';}
function valid(row:ImportTransaction){const a=accounts.allAccountsMap[row.sourceAccountId],c=categories.allTransactionCategoriesMap[row.categoryId];return Number.isSafeInteger(row.time)&&row.time>0&&Number.isSafeInteger(row.sourceAmount)&&row.sourceAmount>0&&!!a&&(!row.originalSourceAccountCurrency||a.currency===row.originalSourceAccountCurrency.toUpperCase())&&!!c&&c.type===row.type-1&&row.isTransactionValid()&&(row.type!==4||(row.destinationAccountId!==row.sourceAccountId&&Number.isSafeInteger(row.destinationAmount)&&row.destinationAmount>0));}
function map(key:number,index:number){if(index<0)delete mapping.value[key];else mapping.value[key]=index;}
function date(row:ImportTransaction,value:string){const time=moment.tz(value,'YYYY-MM-DDTHH:mm',true,scope.timeZone);row.time=time.isValid()?time.unix():0;row.utcOffset=time.utcOffset();}
function money(row:ImportTransaction,key:'sourceAmount'|'destinationAmount',value:string){row[key]=/^\d{1,13}(?:\.\d{1,2})?$/.test(value)?new LedgerDecimal(value).mul(100).toNumber():NaN;}
function reset(){file.value=undefined;table.value=[];rows.value=[];ocrText.value='';finished.value='';batchId.value=crypto.randomUUID();if(picker.value)picker.value.value='';}
async function choose(event:Event){const files=Array.from((event.target as HTMLInputElement).files||[]);if(!files.length)return;reset();file.value=files[0];busy.value=true;error.value='';try{if(files.some(f=>f.size>20*1024*1024)||files.length>20)throw Error('每次最多 20 张，每个文件不超过 20 MB');if(fileType.value==='screenshot'){const result=await recognizeBillImages(files,scope.timeZone,text=>progress.value=text);ocrText.value=result.text;preview(result.items.map(ImportTransaction.of));if(!rows.value.length)error.value='未找到可确认的金额，请查看识别文字或手动补一笔。';}else if(fileType.value.startsWith('custom_')){const response=await services.parseImportCustomFile({fileType:fileType.value,fileEncoding:encoding.value,importFile:file.value!});table.value=response.data.result;mapping.value={};(table.value[0]||[]).forEach((title,index)=>{const known=KNOWN_COLUMN_NAME_MAPPING[title.trim().toLowerCase().replaceAll(' ','').replaceAll('_','').replaceAll('-','')];if(known)mapping.value[known.type]=index;});const example=table.value[1]?.[mapping.value[1]??-1]||'';dateFormat.value=/^\d{4}-\d{2}-\d{2}$/.test(example)?'YYYY-MM-DD':/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/.test(example)?'YYYY-MM-DD HH:mm':'YYYY-MM-DD HH:mm:ss';if([1,3,6,8].every(key=>mapping.value[key]!==undefined))await parseFile();}else await parseFile();}catch(e){error.value=investmentError(e);}finally{busy.value=false;progress.value='';}}
async function parseFile(){if(!file.value)return;busy.value=true;error.value='';try{const response=await services.parseImportTransaction({fileType:fileType.value,fileEncoding:encoding.value,importFile:file.value,columnMapping:mapping.value,hasHeaderLine:true,timeFormat:dateFormat.value,transactionTypeMapping:{收入:2,支出:3,转账:4,余额调整:1,Income:2,Expense:3,Transfer:4},amountDecimalSeparator:'.',amountDigitGroupingSymbol:',',tagSeparator:';',geoSeparator:' ',geoOrder:'lonlat'});preview(response.data.result.items.map(ImportTransaction.of));}catch(e){error.value=investmentError(e);}finally{busy.value=false;}}
function preview(items:ImportTransaction[]){const seen=new Set(ledger.entries.value.map(e=>`${e.time}|${e.type}|${e.accountId}|${e.amount}|${e.comment}`));duplicates.value=new Set();for(const row of items){const rule=keywordMatch(row.comment+' '+row.originalCategoryName,rules);if(rule&&categories.allTransactionCategoriesMap[rule.categoryId]?.type===row.type-1){row.categoryId=rule.categoryId;if(rule.accountId)row.sourceAccountId=rule.accountId;row.tagIds=Array.from(new Set([...row.tagIds,...rule.tagIds]));}row.tagIds=row.tagIds.filter(id=>id&&id!=='0');const key=`${row.time}|${row.type}|${row.sourceAccountId}|${new LedgerDecimal(row.sourceAmount).div(100).toString()}|${row.comment}`;if(seen.has(key))duplicates.value.add(row.index);seen.add(key);row.selected=!duplicates.value.has(row.index);}rows.value=items;}
function applyAccount(){if(bulkAccount.value)for(const row of selected.value)row.sourceAccountId=bulkAccount.value;}
function applyCategory(){const c=categories.allTransactionCategoriesMap[bulkCategory.value];if(c)for(const row of selected.value)if(c.type===row.type-1)row.categoryId=c.id;}
function selectValid(){for(const row of rows.value)row.selected=valid(row)&&!duplicates.value.has(row.index);}
function addRow(){const now=moment().tz(scope.timeZone);const row=ImportTransaction.of({type:3,categoryId:'',originalCategoryName:'',sourceAccountId:'',originalSourceAccountName:'',originalSourceAccountCurrency:'CNY',sourceAmount:0,time:now.unix(),utcOffset:now.utcOffset(),tagIds:[],originalTagNames:[],comment:''},rows.value.length);row.selected=true;rows.value.push(row);limit.value=rows.value.length;}
function commit(){f7.dialog.confirm(`确认把这 ${selected.value.length} 笔账单导入当前账本？账户余额会随账单更新。`,'确认导入',async()=>{busy.value=true;error.value='';try{const request=selected.value.map(row=>{row.bookId=bookId.value;return row.toCreateRequest();});const response=await services.importTransactions({bookId:bookId.value,transactions:request,clientSessionId:batchId.value,batchId:batchId.value,sourceName:file.value?.name||'截图导入'});finished.value=`已导入 ${response.data.result} 笔。可在导入导出中管理此批记录。`;rows.value=[];table.value=[];ocrText.value='';if(fileType.value==='screenshot'&&experience.preferences.deleteImportedScreenshots)window.CYLedgerLocal?.action('deleteImportedScreenshots','{}');await accounts.loadAllAccounts({force:true});}catch(e){error.value=investmentError(e);}finally{busy.value=false;}});}
</script>
<style scoped>
.cy-import-body{padding:12px 14px 90px}.cy-import-file{display:none}.cy-import-field{display:grid;grid-template-columns:90px 1fr;gap:12px;align-items:center;padding:10px 0;font-size:14px}.cy-import-field input,.cy-import-field select,.cy-import-field textarea{min-width:0;width:100%;padding:9px;border:1px solid var(--cy-line);border-radius:8px;background:var(--cy-card);color:var(--cy-ink)}.cy-import-body .cy-button{margin:8px 6px 8px 0}.cy-import-row summary{font-size:14px;line-height:1.8;overflow-wrap:anywhere}.cy-import-row small{display:block;color:var(--cy-muted);padding-left:24px}.cy-import-row b{float:right}.cy-ocr-text{white-space:pre-wrap;max-height:300px;overflow:auto}
</style>
