<template><f7-page class="cy-mobile-surface" @page:afterin="load"><f7-navbar title="数据小卡片" back-link="返回"><f7-nav-right><f7-link @click="add()">添加</f7-link></f7-nav-right></f7-navbar><main class="cy-page-body">
    <p class="cy-helper">拖动卡片调整顺序，点击修改内容和显示范围。</p><p v-if="error" class="cy-message">{{ error }}</p>
    <section class="cy-panel cy-card-settings dragenabled" v-for="(card,index) in experience.preferences.cards" :key="card.id" :data-card-index="index" draggable="true" @dragstart="dragIndex=index" @dragover.prevent @drop.prevent="move(dragIndex,index)"><button @click="edit(card)"><f7-icon f7="square_grid_2x2" /><span>{{ card.title || ledgerCardNames[card.kind] }}<small>{{ periodNames[card.period] }} · {{ widthNames[card.width] }}</small></span></button><button class="cy-card-drag" aria-label="拖动排序" @touchstart.stop="dragIndex=index" @touchmove.stop.prevent="touchMove" @touchend="dragIndex=-1">☰</button><button :disabled="index===0" aria-label="上移卡片" @click="move(index,index-1)">↑</button><button :disabled="index===experience.preferences.cards.length-1" aria-label="下移卡片" @click="move(index,index+1)">↓</button></section>
    <button class="cy-button cy-primary-action" @click="add()">＋ 添加数据小卡片</button>
</main><f7-popup v-model:opened="opened" class="cy-mobile-surface"><f7-page><f7-navbar :title="editing ? '编辑小卡片' : '添加小卡片'"><f7-nav-left><f7-link popup-close>取消</f7-link></f7-nav-left><f7-nav-right><f7-link @click="save">保存</f7-link></f7-nav-right></f7-navbar><main v-if="draft" class="cy-page-body cy-card-form"><section class="cy-panel">
    <label>卡片内容<select v-model="draft.kind"><option v-for="(name,kind) in ledgerCardNames" :key="kind" :value="kind">{{ name }}</option></select></label><label>名称<input v-model="draft.title" maxlength="32" :placeholder="ledgerCardNames[draft.kind]" /></label><label>大小<select v-model.number="draft.width"><option v-for="(name,value) in widthNames" :key="value" :value="Number(value)">{{ name }}</option></select></label><label>时间范围<select v-model="draft.period"><option v-for="(name,value) in periodNames" :key="value" :value="value">{{ name }}</option></select></label>
    <label v-if="draft.kind==='wish'">愿望<select v-model="draft.wishId"><option value="">全部进行中的愿望</option><option v-for="wish in wishes" :key="wish.id" :value="wish.id">{{ wish.data.name }}</option></select></label>
    <LedgerScopeFields v-model:book-ids="draft.bookIds" v-model:account-ids="draft.accountIds" v-model:category-ids="draft.categoryIds" v-model:tag-ids="draft.tagIds" accounts-enabled categories-enabled tags-enabled />
    <label>文字颜色<input type="color" :value="draft.color || '#303637'" @input="draft.color=($event.target as HTMLInputElement).value" /></label><label>背景颜色<input type="color" :value="draft.background || '#ffffff'" @input="draft.background=($event.target as HTMLInputElement).value" /></label><button class="cy-button" @click="draft.color='';draft.background=''">跟随主题颜色</button>
    <label>背景图片<input type="file" accept="image/*" @change="backgroundPhoto" /></label><label>背景不透明度<input type="range" min="0.15" max="1" step="0.05" v-model.number="draft.opacity" /></label><button v-if="draft.image" class="cy-button" @click="draft.image=''">移除背景图片</button><p v-if="error" class="cy-message">{{error}}</p>
    <p v-if="draft.kind==='gold'" class="cy-helper">显示投资账户中已绑定的黄金报价；在资产页添加黄金标的或录入价格后展示。</p><p v-if="['asset','assetTrend','credit','debt'].includes(draft.kind)" class="cy-helper">资产卡片展示账户当前余额或已保存的估值快照。</p>
</section><button v-if="editing" class="cy-button cy-danger" @click="remove">删除小卡片</button></main></f7-page></f7-popup></f7-page></template>
<script setup lang="ts">
import {ref} from 'vue';
import {useLedgerExperienceStore} from '@/stores/ledgerExperience.ts';
import {ledgerCardNames,type LedgerCard} from '@/lib/ledger-preferences.ts';
import LedgerScopeFields from '@/components/mobile/LedgerScopeFields.vue';
import {ledgerWorkspace,type LedgerWorkspaceItem,type LedgerWish} from '@/lib/ledger-workspace.ts';
import {useMobileLedger} from '@/lib/mobile-ledger.ts';
import {investmentError} from '@/lib/investments.ts';
const experience=useLedgerExperienceStore(),data=useMobileLedger({bookIds:()=>[],applyFilters:()=>false}),opened=ref(false),editing=ref(false),draft=ref<LedgerCard>(),dragIndex=ref(-1),error=ref(''),wishes=ref<LedgerWorkspaceItem<LedgerWish>[]>([]);
const periodNames={today:'今天',week:'本周',month:'本月',year:'本年',all:'全部'},widthNames={2:'三分之一',3:'二分之一',4:'三分之二',6:'整行'};
async function load(){try{await data.load(0,1);wishes.value=await ledgerWorkspace.wishes();}catch(e){error.value=investmentError(e);}}
function add(){if(experience.preferences.cards.length>=20){error.value='最多可添加 20 个小卡片';return;}draft.value={id:crypto.randomUUID(),kind:'expense',title:'',period:'month',bookIds:[],accountIds:[],categoryIds:[],tagIds:[],wishId:'',width:3,color:'',background:'',image:'',opacity:1};editing.value=false;opened.value=true;}
async function backgroundPhoto(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file||!draft.value)return;error.value='';try{if(file.size>20*1024*1024)throw Error('图片不能超过 20 MB');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');const scale=Math.min(1,480/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let image=canvas.toDataURL('image/jpeg',.65);if(image.length>70000)image=canvas.toDataURL('image/jpeg',.35);if(image.length>70000)throw Error('图片细节过多，请选择更简洁的背景');draft.value.image=image;draft.value.opacity=1;}catch(e){error.value=investmentError(e);}}
function edit(card:LedgerCard){draft.value=JSON.parse(JSON.stringify(card));editing.value=true;opened.value=true;}
function save(){if(!draft.value)return;experience.set('cards',editing.value?experience.preferences.cards.map(c=>c.id===draft.value!.id?draft.value!:c):[...experience.preferences.cards,draft.value]);opened.value=false;}
function remove(){if(!draft.value)return;experience.set('cards',experience.preferences.cards.filter(c=>c.id!==draft.value!.id));opened.value=false;}
function touchMove(event:TouchEvent){const touch=event.touches[0];if(!touch)return;const target=document.elementFromPoint(touch.clientX,touch.clientY)?.closest('[data-card-index]');if(target){const index=Number(target.getAttribute('data-card-index'));if(index!==dragIndex.value){move(dragIndex.value,index);dragIndex.value=index;}}}
function move(from:number,to:number){const cards=[...experience.preferences.cards];if(from<0||to<0||from>=cards.length||to>=cards.length)return;cards.splice(to,0,cards.splice(from,1)[0]!);experience.set('cards',cards);}
</script>
<style scoped>.cy-helper{font-size:12px;color:var(--cy-muted);line-height:1.7}.cy-card-settings{display:flex;align-items:center;gap:8px}.cy-card-settings button{background:transparent;border:0;color:var(--cy-ink);padding:8px}.cy-card-drag{touch-action:none}.cy-card-settings>button:first-child{flex:1;display:flex;align-items:center;gap:14px;text-align:left}.cy-card-settings span{font-size:15px}.cy-card-settings small{display:block;font-size:11px;color:var(--cy-muted);margin-top:7px}.cy-card-form label{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 0;font-size:14px;border-bottom:1px solid var(--cy-line)}.cy-card-form select,.cy-card-form input:not([type=color]){max-width:65%;border:0;background:transparent;text-align:right;color:var(--cy-ink);padding:5px}.cy-card-form input[type=color]{border:0;width:36px;height:28px}.cy-danger{color:var(--cy-expense)}</style>
