<template><f7-page class="cy-mobile-surface" @page:afterin="load"><f7-navbar title="更多设置" back-link="返回" /><main class="cy-settings-body"><p v-if="error" class="cy-message">{{ error }}</p>
<f7-block-title>安全设置</f7-block-title><f7-list strong inset><f7-list-item title="指纹 / 面容解锁"><template #after><f7-toggle :checked="security.biometric" :disabled="!native" @toggle:change="nativeAction('biometric',$event)" /></template></f7-list-item><f7-list-item title="手势密码" :after="security.gesture?'已启用':'未启用'" link="#" @click="nativeAction('gesture')" /><f7-list-item v-if="security.gesture" title="关闭手势密码" link="#" @click="nativeAction('gestureOff')" /></f7-list>
<template v-for="section in sections" :key="section.title"><f7-block-title>{{ section.title }}</f7-block-title><f7-list strong inset><template v-for="row in section.rows" :key="row.key"><f7-list-input v-if="row.options" :label="row.name" type="select" :value="p[row.key]" @change="change(row.key,($event.target as HTMLSelectElement).value)"><option v-for="choice in row.options" :key="choice.value" :value="choice.value">{{ choice.name }}</option></f7-list-input><f7-list-item v-else :title="row.name"><template #after><f7-toggle :checked="Boolean(p[row.key])" @toggle:change="experience.set(row.key,$event)" /></template></f7-list-item></template></f7-list></template>
<f7-block-title>记账与日期</f7-block-title><f7-list strong inset><f7-list-input label="月起始日" type="select" :value="p.monthStart" @change="experience.set('monthStart',Number(($event.target as HTMLSelectElement).value))"><option v-for="day in 28" :key="day" :value="day">每月 {{ day }} 日</option></f7-list-input><f7-list-input label="周起始日" type="select" :value="settings.appSettings.calendarWeekStart" @change="settings.setCalendarPreference('calendarWeekStart',Number(($event.target as HTMLSelectElement).value))"><option value="0">星期日</option><option value="1">星期一</option><option value="6">星期六</option></f7-list-input><f7-list-input label="默认账户" type="select" :value="p.defaultAccountId" @change="experience.set('defaultAccountId',($event.target as HTMLSelectElement).value)"><option value="category">分类上次使用的账户</option><option value="last">上次记账的账户</option><option v-for="account in accounts.allPlainAccounts.filter(a=>!a.subAccounts?.length)" :key="account.id" :value="account.id">{{ account.name }}</option></f7-list-input><f7-list-item title="自动获取位置"><template #after><f7-toggle :checked="settings.appSettings.autoGetCurrentGeoLocation" @toggle:change="settings.setAutoGetCurrentGeoLocation($event)" /></template></f7-list-item><f7-list-item title="保留未完成的账单草稿"><template #after><f7-toggle :checked="settings.appSettings.autoSaveTransactionDraft==='enabled'" @toggle:change="settings.setAutoSaveTransactionDraft($event?'enabled':'disabled')" /></template></f7-list-item><f7-list-item title="记账提醒" :after="security.reminder || '未设置'" link="#" @click="nativeAction('reminder')" /><f7-list-item title="分类关键词" link="/keywords" /><f7-list-item title="记账模板" link="/template/list" /><f7-list-item title="周期记账" link="/schedule/list" /><f7-list-item title="会计时区" :after="timeZone" link="#" @click="showZone=true" /></f7-list>
<f7-block-title>日历</f7-block-title><f7-list strong inset><f7-list-item v-for="row in calendarRows" :key="row.key" :title="row.name"><template #after><f7-toggle :checked="Boolean(settings.appSettings[row.key])" @toggle:change="settings.setCalendarPreference(row.key,$event)" /></template></f7-list-item></f7-list>
<f7-block-title>外观与模块</f7-block-title><f7-list strong inset><f7-list-item title="字体大小" link="/settings/textsize" /><f7-list-item title="首页数据小卡片" link="/settings/cards" /><f7-list-item title="主题外观" link="/settings/appearance" /></f7-list>
<details class="cy-panel cy-settings-details"><summary>特殊账单图标</summary><label v-for="(name,key) in specialNames" :key="key">{{ name }}<select :value="p.specialIcons[key]" @change="experience.set('specialIcons',{...p.specialIcons,[key]:($event.target as HTMLSelectElement).value})"><option v-for="icon in iconOptions" :key="icon.value" :value="icon.value">{{ icon.name }}</option></select><f7-icon :f7="p.specialIcons[key]" /></label></details>
<details class="cy-panel cy-settings-details"><summary>主界面模块</summary><div v-for="(tab,index) in p.tabs" :key="tab" class="cy-tab-setting"><span>{{ ledgerTabNames[tab] }}</span><button :disabled="index===0" @click="moveTab(index,-1)">↑</button><button :disabled="index===p.tabs.length-1" @click="moveTab(index,1)">↓</button><button v-if="!['home','settings'].includes(tab)" @click="experience.set('tabs',p.tabs.filter(t=>t!==tab))">隐藏</button></div><button v-for="tab in hiddenTabs" :key="tab" class="cy-button" @click="experience.set('tabs',[...p.tabs,tab])">显示{{ ledgerTabNames[tab] }}</button></details>
<f7-block-title>系统设置</f7-block-title><f7-list strong inset><f7-list-item title="退出时确认"><template #after><f7-toggle :checked="p.exitConfirm" @toggle:change="experience.set('exitConfirm',$event)" /></template></f7-list-item><f7-list-item title="隐藏最近任务中的内容"><template #after><f7-toggle :checked="p.hideRecents" @toggle:change="experience.set('hideRecents',$event)" /></template></f7-list-item><f7-list-item title="系统快捷开关" link="#" @click="nativeAction('quickTile')" /><f7-list-item title="系统权限设置" link="#" @click="nativeAction('permissions')" /><f7-list-item title="汇率数据" link="/exchange_rates" /></f7-list><list-item-selection-popup value-type="item" key-field="name" value-field="name" title-field="displayNameWithUtcOffset" title="会计时区" :enable-filter="true" :items="allTimezones" v-model:show="showZone" v-model="timeZone" /></main></f7-page></template>
<script setup lang="ts">
import {computed,ref,onMounted,onUnmounted} from 'vue';
import {useLedgerExperienceStore} from '@/stores/ledgerExperience.ts';
import {useSettingsStore} from '@/stores/setting.ts';
import {useAccountsStore} from '@/stores/account.ts';
import {useAppSettingPageBase} from '@/views/base/settings/AppSettingsPageBase.ts';
import {ledgerTabNames,type LedgerPreferences,type LedgerTab} from '@/lib/ledger-preferences.ts';
import {isNativePersonalMode} from '@/lib/native.ts';
const experience=useLedgerExperienceStore(),settings=useSettingsStore(),accounts=useAccountsStore(),p=computed(()=>experience.preferences),native=isNativePersonalMode(),error=ref(''),showZone=ref(false),security=ref({biometric:false,gesture:false,reminder:''});
const {allTimezones,timeZone}=useAppSettingPageBase();
interface Row{key:keyof LedgerPreferences;name:string;options?:{value:string;name:string}[]}
const options=(items:Record<string,string>)=>Object.entries(items).map(([value,name])=>({value,name}));
const sections:{title:string;rows:Row[]}[]=[{title:'显示设置',rows:[{key:'multiCurrency',name:'多币种记账'},{key:'remarkFirst',name:'优先显示备注'},{key:'simpleCategory',name:'简化分类名称'},{key:'showTime',name:'显示记账时间'},{key:'showOriginal',name:'显示优惠前金额'},{key:'showAccountIcon',name:'显示账户图标'},{key:'lineIcons',name:'线性分类图标'},{key:'colorScheme',name:'金额颜色',options:options({'red-expense':'支出红色 · 收入绿色','green-expense':'支出绿色 · 收入红色',monochrome:'跟随文字颜色'})},{key:'navigationText',name:'导航栏显示文字'},{key:'navigationStyle',name:'导航栏样式',options:options({floating:'悬浮',glass:'透明',fixed:'固定'})}]},{title:'快捷记账',rows:[{key:'deleteImportedScreenshots',name:'导入成功后请求删除原截图'},{key:'vibration',name:'键盘振动'},{key:'historicalRemarks',name:'历史备注提示'},{key:'lowBalance',name:'余额不足提醒'},{key:'keyboard',name:'键盘数字顺序',options:options({ascending:'1 2 3 在上方',descending:'7 8 9 在上方'})}]},{title:'首页',rows:[{key:'hideHero',name:'隐藏首页收支概览'},{key:'hideAdd',name:'隐藏首页记账按钮'},{key:'pullAction',name:'首页下拉操作',options:options({add:'添加记账',refresh:'刷新账单',none:'无操作'})},{key:'floatPosition',name:'悬浮按钮位置',options:options({hidden:'隐藏',left:'左侧',right:'右侧'})},{key:'floatAction',name:'悬浮按钮功能',options:options({add:'手动记账',import:'导入账单'})}]}];
const calendarRows=[{key:'calendarShowLunar' as const,name:'显示农历'},{key:'calendarShowRepayments' as const,name:'显示还款'},{key:'calendarShowDeposits' as const,name:'显示定存到期'}];
const specialNames={transfer:'转账',repayment:'还款',borrow:'借入',lend:'借出',adjustment:'余额调整'},iconOptions=options({arrow_right_arrow_left:'双向箭头',creditcard:'银行卡',arrow_down_left:'转入箭头',arrow_up_right:'转出箭头',equal_circle:'等号',banknote:'钞票',arrow_2_squarepath:'循环箭头',wallet:'钱包'});
const hiddenTabs=computed(()=>(Object.keys(ledgerTabNames) as LedgerTab[]).filter(t=>!p.value.tabs.includes(t)));
async function load(){await accounts.loadAllAccounts({force:false}).catch(()=>{});refreshSecurity();}
function refreshSecurity(){try{security.value=JSON.parse(window.CYLedgerLocal?.status()||'{}');}catch{error.value='无法读取手机设置';}}
onMounted(()=>window.addEventListener('cyledger-native-change',refreshSecurity));
onUnmounted(()=>window.removeEventListener('cyledger-native-change',refreshSecurity));
function change(key:keyof LedgerPreferences,value:string){experience.set(key,value as never);}
function moveTab(index:number,offset:number){const tabs=[...p.value.tabs],to=index+offset;if(to<0||to>=tabs.length)return;tabs.splice(to,0,tabs.splice(index,1)[0]!);experience.set('tabs',tabs);}
function nativeAction(action:string,value?:boolean){if(!window.CYLedgerLocal){error.value='此功能需在 OpenBill 手机应用中使用';return;}window.CYLedgerLocal.action(action,JSON.stringify({enabled:value}));setTimeout(refreshSecurity,600);}
</script>
<style scoped>.cy-settings-body{padding:0 0 30px;max-width:720px;margin:auto}.cy-settings-details{margin:14px 16px}.cy-settings-details summary{font-size:15px;cursor:pointer}.cy-settings-details label{display:flex;align-items:center;gap:10px;padding-top:18px;font-size:14px}.cy-settings-details select{margin-left:auto;color:var(--cy-ink);background:transparent;border:0;max-width:60%}.cy-tab-setting{display:flex;gap:8px;align-items:center;padding:15px 0;border-bottom:1px solid var(--cy-line)}.cy-tab-setting span{flex:1}.cy-tab-setting button{background:transparent;border:0;color:var(--cy-muted);padding:5px 9px}</style>
