package com.cyledger.android;

import android.app.*;import android.content.*;import android.hardware.biometrics.BiometricPrompt;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.webkit.*;import android.widget.*;import android.view.View;
import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.*;import javax.crypto.SecretKeyFactory;import javax.crypto.spec.PBEKeySpec;

final class LocalBridge {
 static final int RESTORE=801,EXPORT=802,CREDENTIAL=803;private final MainActivity activity;private final SharedPreferences prefs;private final ExecutorService io=Executors.newSingleThreadExecutor();private final Handler handler=new Handler(Looper.getMainLooper());private WebView web;private boolean unlocked,authShowing,busy;private long stopped;private Runnable credentialSuccess;private File pendingExport;private AlertDialog lockDialog;private String cachedSettings="{}";private final ArrayList<Uri> importedImages=new ArrayList<>();
 LocalBridge(MainActivity activity){this.activity=activity;prefs=activity.getSharedPreferences("local_settings",Context.MODE_PRIVATE);}
 void attach(WebView view){web=view;}
 private boolean trusted(){return web!=null&&activity.isLocalPage(web.getUrl());}
 private void ui(Runnable run){handler.post(()->{if(trusted()&&unlocked)run.run();});}
 private void toast(String text){Toast.makeText(activity,text,Toast.LENGTH_LONG).show();}
 private void event(String text){if(web!=null)web.evaluateJavascript("window.dispatchEvent(new CustomEvent('cyledger-native-change',{detail:"+JSONObject.quote(text)+"}))",null);}
 private File backupsDir(){File root=new File(activity.getFilesDir(),"backups");root.mkdirs();return root;}
 private File backupFile(String name)throws Exception{if(name==null||!name.matches("CYLedger-[a-zA-Z0-9-]+\\.zip"))throw new Exception();File file=new File(backupsDir(),name);if(!file.getCanonicalFile().getParentFile().equals(backupsDir().getCanonicalFile()))throw new Exception();return file;}
 @JavascriptInterface public String status(){try{return new JSONObject().put("biometric",prefs.getBoolean("biometric",false)).put("gesture",prefs.contains("pattern")).put("autoBackup",prefs.getBoolean("autoBackup",false)).put("reminder",prefs.getString("reminder","")).toString();}catch(Exception e){return "{}";}}
 @JavascriptInterface public String backups(){try{JSONArray rows=new JSONArray();File[] files=backupsDir().listFiles();if(files!=null){Arrays.sort(files,(a,b)->Long.compare(b.lastModified(),a.lastModified()));for(File file:files)if(file.getName().endsWith(".zip"))rows.put(new JSONObject().put("name",file.getName()).put("size",Long.toString(file.length())).put("time",file.lastModified()));}return rows.toString();}catch(Exception e){return "[]";}}
 @JavascriptInterface public void preferences(String json){ui(()->{try{if(json.length()>200000)return;JSONObject data=new JSONObject(json);prefs.edit().putBoolean("exitConfirm",data.optBoolean("exitConfirm")).putBoolean("hideRecents",data.optBoolean("hideRecents")).apply();applyPrivacy();}catch(Exception ignored){}});}
 @JavascriptInterface public void settings(String json){ui(()->{try{if(json.length()>2000000)return;JSONObject data=new JSONObject(json);Iterator<String> keys=data.keys();while(keys.hasNext()){String key=keys.next();if(!key.equals("ebk_app_settings")&&!key.startsWith("cy_ledger_experience_"))return;}cachedSettings=json;if(prefs.getBoolean("autoBackup",false)&&!day().equals(prefs.getString("backupDay","")))createBackup(json,true,null);}catch(Exception ignored){}});}
 @JavascriptInterface public void backup(String json){ui(()->createBackup(json,false,null));}
 @JavascriptInterface public void restore(){ui(()->{if(busy)return;Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE);activity.startActivityForResult(intent,RESTORE);});}
 @JavascriptInterface public void exportBackup(String name){ui(()->{try{pendingExport=backupFile(name);if(!pendingExport.isFile())throw new Exception();Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,name);activity.startActivityForResult(intent,EXPORT);}catch(Exception e){toast("备份文件不存在");}});}
 @JavascriptInterface public void deleteBackup(String name){ui(()->new AlertDialog.Builder(activity).setTitle("删除这份备份？").setMessage(name).setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{try{File file=backupFile(name);if(!file.delete())throw new Exception();event("备份已删除");}catch(Exception e){toast("备份删除失败");}}).show());}
 @JavascriptInterface public void action(String action,String payload){ui(()->{try{JSONObject data=new JSONObject(payload);switch(action){case "deleteImportedScreenshots":deleteImportedImages();break;case "biometric":authenticateDevice(()->{prefs.edit().putBoolean("biometric",data.optBoolean("enabled")).apply();event("");});break;case "gesture":setupPattern();break;case "gestureOff":authenticateDevice(()->{prefs.edit().remove("pattern").remove("salt").apply();event("");});break;case "autoBackup":prefs.edit().putBoolean("autoBackup",data.optBoolean("enabled")).apply();event("");if(data.optBoolean("enabled"))createBackup(cachedSettings,true,null);break;case "settingsRestored":new File(activity.getFilesDir(),"ledger/settings.json").delete();break;case "permissions":activity.startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+activity.getPackageName())));break;case "quickTile":quickTile();break;case "reminder":reminder();break;}}catch(Exception e){toast("设置未完成，请重试");}});}
 void selectedFiles(Uri[] uris){importedImages.clear();if(uris==null)return;for(Uri uri:uris){try{String type=activity.getContentResolver().getType(uri);if(type!=null&&type.startsWith("image/"))importedImages.add(uri);}catch(Exception ignored){}}}
 private void deleteImportedImages(){if(importedImages.isEmpty())return;if(Build.VERSION.SDK_INT<30){toast("账单已导入，请在相册中手动删除原截图");return;}ArrayList<Uri> media=new ArrayList<>();for(Uri uri:importedImages){try{Uri resolved=android.provider.MediaStore.AUTHORITY.equals(uri.getAuthority())?uri:android.provider.MediaStore.getMediaUri(activity,uri);if(resolved!=null&&android.provider.MediaStore.AUTHORITY.equals(resolved.getAuthority()))media.add(resolved);}catch(Exception ignored){}}importedImages.clear();if(media.isEmpty()){toast("账单已导入；此文件来源不支持删除，请在相册中处理");return;}try{PendingIntent request=android.provider.MediaStore.createDeleteRequest(activity.getContentResolver(),media);activity.startIntentSenderForResult(request.getIntentSender(),805,null,0,0,0);}catch(Exception e){toast("账单已导入，请在相册中手动删除原截图");}}
 private String day(){return new SimpleDateFormat("yyyyMMdd",Locale.ROOT).format(new Date());}
 private void createBackup(String settings,boolean automatic,Runnable after){if(busy)return;busy=true;if(!automatic)event("正在创建完整备份…");io.execute(()->{String message="备份失败，请重试";boolean success=false;try{String name="CYLedger-"+new SimpleDateFormat("yyyyMMdd-HHmmss",Locale.ROOT).format(new Date())+"-"+Integer.toHexString(new SecureRandom().nextInt())+".zip";File destination=backupFile(name);JSONObject result=new JSONObject(NativeBridge.backup(new File(activity.getFilesDir(),"ledger").getAbsolutePath(),destination.getAbsolutePath(),settings));if(result.has("error"))throw new Exception();prefs.edit().putString("backupDay",day()).apply();message="完整备份已保存到手机";success=true;}catch(Exception ignored){}final String result=message;final boolean ok=success;handler.post(()->{busy=false;if(!automatic||!ok)event(result);else event("");if(ok&&after!=null)after.run();});});}
 void activityResult(int request,int result,Intent data){if(request==CREDENTIAL){Runnable next=credentialSuccess;credentialSuccess=null;authShowing=false;if(result==Activity.RESULT_OK&&next!=null)next.run();else if(!unlocked)showLock();return;}if(result!=Activity.RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();if(request==EXPORT&&pendingExport!=null){File file=pendingExport;pendingExport=null;io.execute(()->{try(InputStream in=new FileInputStream(file);OutputStream out=activity.getContentResolver().openOutputStream(uri)){copy(in,out,2L*1024*1024*1024);handler.post(()->event("备份文件已导出"));}catch(Exception e){handler.post(()->event("导出失败，请重新选择保存位置"));}});}else if(request==RESTORE){if(busy)return;busy=true;event("正在校验备份…");io.execute(()->{File input=new File(activity.getCacheDir(),"restore-"+UUID.randomUUID()+".zip");String staged=null;try(InputStream in=activity.getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(input)){copy(in,out,2L*1024*1024*1024);}catch(Exception e){input.delete();handler.post(()->{busy=false;event("无法读取备份，原账本未更改");});return;}try{JSONObject resultJSON=new JSONObject(NativeBridge.stageRestore(input.getAbsolutePath(),activity.getFilesDir().getAbsolutePath()));if(resultJSON.has("error"))throw new Exception();staged=resultJSON.getString("value");}catch(Exception ignored){}input.delete();final String stage=staged;handler.post(()->{busy=false;if(stage==null){event("备份校验失败，原账本未更改");return;}new AlertDialog.Builder(activity).setTitle("恢复这份备份？").setMessage("当前账本将替换为备份内容。恢复前会自动保存一份完整备份，应用随后重新打开。").setNegativeButton("取消",(d,w)->MaintenanceActivity.removeTree(new File(stage))).setPositiveButton("恢复",(d,w)->createBackup(cachedSettings,false,()->{web.setVisibility(View.INVISIBLE);Intent intent=new Intent(activity,MaintenanceActivity.class).putExtra("stage",stage).putExtra("pid",android.os.Process.myPid());activity.startActivity(intent);})).show();});});}}
 static void copy(InputStream in,OutputStream out,long max)throws Exception{if(in==null||out==null)throw new Exception();byte[] buffer=new byte[65536];long size=0;int n;while((n=in.read(buffer))!=-1){size+=n;if(size>max)throw new Exception();out.write(buffer,0,n);}out.flush();}
 boolean exitConfirm(){return prefs.getBoolean("exitConfirm",false);}
 void applyPrivacy(){boolean secure=prefs.getBoolean("hideRecents",false)||prefs.getBoolean("biometric",false)||prefs.contains("pattern");if(Build.VERSION.SDK_INT>=33)activity.setRecentsScreenshotEnabled(!secure);else if(secure)activity.getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAG_SECURE);else activity.getWindow().clearFlags(android.view.WindowManager.LayoutParams.FLAG_SECURE);}
 void stopped(){stopped=System.currentTimeMillis();if(web!=null&&(prefs.getBoolean("biometric",false)||prefs.contains("pattern")))web.setVisibility(View.INVISIBLE);}
 void resumed(){applyPrivacy();if(stopped>0&&System.currentTimeMillis()-stopped>30000)unlocked=false;if(web!=null)ensureUnlocked(()->web.setVisibility(View.VISIBLE));}
 void ensureUnlocked(Runnable next){if(unlocked||(!prefs.getBoolean("biometric",false)&&!prefs.contains("pattern"))){unlocked=true;next.run();return;}if(web!=null)web.setVisibility(View.INVISIBLE);onUnlock=next;showLock();}
 private Runnable onUnlock;
 private void unlocked(){unlocked=true;authShowing=false;if(lockDialog!=null)lockDialog.dismiss();if(web!=null)web.setVisibility(View.VISIBLE);if(onUnlock!=null){Runnable next=onUnlock;onUnlock=null;next.run();}}
 private void showLock(){if(authShowing||activity.isFinishing()||(lockDialog!=null&&lockDialog.isShowing()))return;authShowing=true;LinearLayout box=new LinearLayout(activity);box.setOrientation(LinearLayout.VERTICAL);TextView label=new TextView(activity);label.setText("解锁后查看账本");label.setTextSize(20);label.setPadding(32,28,32,20);box.addView(label);if(prefs.contains("pattern")){PatternView pattern=new PatternView(activity,value->{long until=prefs.getLong("lockUntil",0);if(System.currentTimeMillis()<until){label.setText("请稍后再试，或使用系统解锁");return;}if(checkPattern(value)){prefs.edit().putInt("failures",0).apply();unlocked();}else{int failures=prefs.getInt("failures",0)+1;prefs.edit().putInt("failures",failures).putLong("lockUntil",failures>=5?System.currentTimeMillis()+60000:0).apply();label.setText(failures>=5?"错误次数较多，请一分钟后重试":"手势不正确，请重试");}});box.addView(pattern,new LinearLayout.LayoutParams(-1,(int)(300*activity.getResources().getDisplayMetrics().density)));}Button system=new Button(activity);system.setText("指纹 / 面容 / 系统密码解锁");system.setOnClickListener(v->{authShowing=false;authenticateDevice(this::unlocked);});box.addView(system);lockDialog=new AlertDialog.Builder(activity).setView(box).setCancelable(false).create();lockDialog.show();if(prefs.getBoolean("biometric",false)){authShowing=false;authenticateDevice(this::unlocked);}}
 private void authenticateDevice(Runnable success){KeyguardManager keyguard=activity.getSystemService(KeyguardManager.class);if(!keyguard.isDeviceSecure()){authShowing=false;toast("请先在手机系统设置中启用锁屏密码");return;}authShowing=true;if(Build.VERSION.SDK_INT>=30){BiometricPrompt prompt=new BiometricPrompt.Builder(activity).setTitle("解锁 CYLedger").setAllowedAuthenticators(android.hardware.biometrics.BiometricManager.Authenticators.BIOMETRIC_STRONG|android.hardware.biometrics.BiometricManager.Authenticators.DEVICE_CREDENTIAL).build();prompt.authenticate(new CancellationSignal(),activity.getMainExecutor(),new BiometricPrompt.AuthenticationCallback(){@Override public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult result){authShowing=false;success.run();}@Override public void onAuthenticationError(int code,CharSequence message){authShowing=false;toast(message.toString());}});}else{credentialSuccess=success;activity.startActivityForResult(keyguard.createConfirmDeviceCredentialIntent("解锁 CYLedger","确认手机锁屏密码"),CREDENTIAL);}}
 private String hash(String pattern,String salt)throws Exception{PBEKeySpec spec=new PBEKeySpec(pattern.toCharArray(),android.util.Base64.decode(salt,0),120000,256);byte[] hash=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();spec.clearPassword();return android.util.Base64.encodeToString(hash,2);}
 private boolean checkPattern(String pattern){try{return MessageDigest.isEqual(hash(pattern,prefs.getString("salt","")).getBytes(StandardCharsets.UTF_8),prefs.getString("pattern","").getBytes(StandardCharsets.UTF_8));}catch(Exception e){return false;}}
 private void setupPattern(){authenticateDevice(()->{final String[] first={null};LinearLayout box=new LinearLayout(activity);box.setOrientation(1);TextView label=new TextView(activity);label.setText("连接至少四个点");label.setPadding(32,24,32,16);box.addView(label);AlertDialog dialog=new AlertDialog.Builder(activity).setTitle("设置手势密码").setView(box).setNegativeButton("取消",null).create();box.addView(new PatternView(activity,value->{if(value.length()<4){label.setText("至少连接四个点");return;}if(first[0]==null){first[0]=value;label.setText("请再次绘制相同手势");return;}if(!first[0].equals(value)){first[0]=null;label.setText("两次不一致，请重新绘制");return;}try{byte[] bytes=new byte[16];new SecureRandom().nextBytes(bytes);String salt=android.util.Base64.encodeToString(bytes,2);prefs.edit().putString("salt",salt).putString("pattern",hash(value,salt)).putInt("failures",0).putLong("lockUntil",0).apply();applyPrivacy();dialog.dismiss();event("");}catch(Exception e){toast("手势未保存，请重试");}}),new LinearLayout.LayoutParams(-1,(int)(300*activity.getResources().getDisplayMetrics().density)));dialog.show();});}
 private void quickTile(){if(Build.VERSION.SDK_INT>=33){activity.getSystemService(android.app.StatusBarManager.class).requestAddTileService(new ComponentName(activity,LedgerTileService.class),"记一笔",android.graphics.drawable.Icon.createWithResource(activity,android.R.drawable.ic_input_add),activity.getMainExecutor(),result->toast(result==android.app.StatusBarManager.TILE_ADD_REQUEST_RESULT_TILE_ADDED?"快捷开关已添加":"可从系统下拉面板编辑快捷开关"));}else toast("下拉系统快捷面板，选择编辑，添加 CYLedger 记一笔");}
 private void reminder(){String current=prefs.getString("reminder","21:00");String[] parts=current.isEmpty()?new String[]{"21","00"}:current.split(":");TimePickerDialog dialog=new TimePickerDialog(activity,(view,h,m)->{prefs.edit().putString("reminder",String.format(Locale.ROOT,"%02d:%02d",h,m)).apply();DailyReminderReceiver.schedule(activity);if(Build.VERSION.SDK_INT>=33)activity.requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},701);event("");},Integer.parseInt(parts[0]),Integer.parseInt(parts[1]),true);dialog.setButton(DialogInterface.BUTTON_NEUTRAL,"关闭提醒",(d,w)->{prefs.edit().remove("reminder").apply();DailyReminderReceiver.schedule(activity);event("");});dialog.show();}
 void destroy(){io.shutdown();}
}
